### ISSUE TITLE
numbers in keys are not unusual

### ISSUE THREAD

**Issue by stephankn** [taginfo/taginfo#124]
The Characters in keys report lists numbers in category C with this explanation "like B but with uppercase latin letters or letters from other alphabets."

While uppercase letters or letters from other alphabets are certainly unusual tagging and often undesired, a number is IMHO wrong classified in this category.

tags like "fuel:e10" are quite common.

I suggest to extend category "B" to include numbers, so it would be "ike A but with one or more colons (:) inside or numbers."

**Comment by joto** [comment]
The whole character category scheme probably has to be extended to be useful. In most cases I have seen, keys with numbers are just bogus. Yes, there are some cases where they are sensible, but I am not sure how to differentiate. One big problem are tags such as `name1` or so used when objects have multiple names. Unfortunately your example `fuel:e10` looks to the computer just like such a case...

**Comment by stephankn** [comment]
As no easy fix is possible, closing issue.
