### ISSUE TITLE
Wiki image missing in documentation query

### ISSUE THREAD

**Issue by bhousel** [taginfo/taginfo#167]
I notice we're not getting image thumbnails anymore in iD when we do a documentation lookup.

 [Relevant code in iD](https://github.com/openstreetmap/iD/blob/2e83ed2a9e126a382d970e3862fff57f1237643e/js/id/ui/tag_reference.js#L54-L61)

<img width="958" alt="screenshot 2016-02-04 09 51 18" src="https://cloud.githubusercontent.com/assets/38784/12818422/e045ecfc-cb24-11e5-8997-6b30d2600391.png">

Maybe related to 748d8c2?

**Comment by joto** [comment]
Something changed in the wiki API and the taginfo script doing the image update broke. I have fixed the script, this should restore some of the images, but there is another problem we have to fix before all the images will be back.

**Comment by bhousel** [comment]
Hey @joto this seems fixed, can it be closed?
