### ISSUE TITLE
Link to Wikidata IDs

### ISSUE THREAD

**Issue by pigsonthewing** [taginfo/taginfo#197]
On pages referencing Wikidata IDs (known as "QIDs", with regex: Q\d+), like:

- https://taginfo.openstreetmap.org/keys/network%3Awikidata
- https://taginfo.openstreetmap.org/tags/network%3Awikidata=Q448199

please make the QID a link, in the format:

https://www.wikidata.org/wiki/Q448199

**Comment by joto** [comment]
Hm. Not sure I want to make special cases for special tag values. On the first page you mention, the key page, all the links go to the tag value pages anyway, I can't change that. On the tag pages, there is  no good place currently to put a link like that. Maybe add a link similar to what is done on the `type=*` pages (for instance https://taginfo.openstreetmap.org/tags/type=restriction the "See also the relation type page: restriction").

**Comment by pigsonthewing** [comment]
Yes, something like that would do. You could also fetch and display the label from the Wikidata item.

**Comment by joto** [comment]
This now works. See for example https://taginfo.openstreetmap.org/tags/wikidata=Q513146 (the Links section on the Overview tab)

**Comment by pigsonthewing** [comment]
> 
> 
> This now works. See for example https://taginfo.openstreetmap.org/tags/wikidata=Q513146 (the Links section on the Overview tab)

This is working for your example, but not for the one in my OP:

https://taginfo.openstreetmap.org/tags/network%3Awikidata=Q448199

**Comment by joto** [comment]
Taginfo can't just magically know how to interpret all tags that are out there. It has a hardcoded list of well-known and often used tags, one of which is `wikidata`. `network:wikidata` isn't on that list.
