### ISSUE TITLE
data for combinations is self contradictory

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#205]
> Data from: 2017-06-14 00:59 UTC

https://taginfo.openstreetmap.org/keys/parking#combinations - 304 639 entries that also have access key

but

https://taginfo.openstreetmap.org/tags/access=private#combinations - 187 457 with access=private and amenity=parking
https://taginfo.openstreetmap.org/tags/access=customers#combinations 125 083 with access=customers and amenity=parking

187457 + 125083 = 312540, what alone is more than 304 639

Given that count of access=private+amenity=parking combined with count access=customers+amenity=parking should not be greater than count of access=*+amenity=parking something went wrong.

**Comment by joto** [comment]
The first link is for key `parking`, not the tag `amenity=parking`. The numbers on https://taginfo.openstreetmap.org/tags/amenity=parking#combinations fit better.

**Comment by matkoniecz** [comment]
Thanks, I expected something like that.
