### ISSUE TITLE
List of project tags seems to be missing entries

### ISSUE THREAD

**Issue by simonpoole** [taginfo/taginfo#213]
To re-create:
Go to https://taginfo.openstreetmap.org/projects/vespucci#tags and filter for "highway" you get three pages of stuff none of which contain highway=turning_circle and a couple of other highway + value combinations. 

However filtering for turning_circle will find the entry, note filtering for =turning_circle doesn't seem to work so maybe it is an error in the project file, but checking didn't show anything.

**Comment by joto** [comment]
This should work now.

Filtering `=turning_circle` is not supposed to work, it just uses simple substring match, so just use `turning_circle` without the equal sign here. That's different than in the search field.

**Comment by simonpoole** [comment]
Fix confirmed, thanks again
