### ISSUE TITLE
Link to Wikidata entity for a tag

### ISSUE THREAD

**Issue by 1ec5** [taginfo/taginfo#219]
A number of tag infoboxes at the OSM Wiki link to a corresponding Wikidata entity ([example](https://wiki.openstreetmap.org/wiki/Key:name:pronunciation)). taginfo could include that link somewhere on the tag pages. Perhaps it could even use a Wikidata dump or the Wikidata API (the fast REST API, not the SPARQL endpoint) to fetch a word describing the tag in the user’s language, as a fallback if there isn’t a wiki page yet in the user’s language for that tag.

/cc @planemad

**Comment by planemad** [comment]
There's around 1100 Wikidata items now tagged with an OSM tag. Here's a SPARQL query of these items with corresponding OSM tags and associated sitelinks: http://tinyurl.com/y9wofodz 

Having this in taginfo can be super useful, especially showing related images from commons that describe the tag.

**Comment by joto** [comment]
@1ec5 Maybe you chose a bad example, but I fail to see why the link to the "International Phonetic Alphabet" on the wikidata site from the `Key:name:pronunciation` gives me any useful information. The wikipedia links coming up in the table of query results @planemad mentioned could be useful, not sure about the rest.

I have long ago written the code to parse the `Q` number out of the wiki and into the taginfo database, but I think it isn't available in the taginfo API yet. Maybe somebody wants to play with that and demonstrate some use cases. I don't know myself enough about what's in wikidata and how it could be useful.

See also #197.

**Comment by 1ec5** [comment]
Yeah, I did choose a poor example at random. A better example is [`amenity=baby_hatch`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbaby_hatch). [The Wikidata entity](https://www.wikidata.org/wiki/Q745455) is labeled in 20 languages, compared to the 11 in the OSM Wiki itself. So this would be a way of supplementing the OSM Wiki for languages that have relatively poor coverage there.

As for the API, an editor or data inspector might want to provide a user-friendly, localized description for a feature tagged with this tag. I can think of some places in iD’s UI that could display a Wikidata-derived description in cases where no preset matches. For example, clicking an ℹ️ button in the raw tag editor opens a taginfo description of the tag, but it’s almost always in English or German, regardless of the user’s language.

**Comment by ImreSamu** [comment]
>So this would be a way of supplementing the OSM Wiki for languages 
>that have relatively poor coverage there.

An alternative solution for brainstorming:
imho: it would be better if we create a new (external?) osm metadata project 
and merge translations  from
*  iD editor translations:   https://github.com/openstreetmap/iD/tree/master/dist/locales
*  JOSM translations
*  Wikidata labels
*  OSM wiki
*  OSM Tagfinder: https://github.com/geometalab/OSMTagFinder 
         *  "thesaurus and an adapted domain-specific semantic net" ???
* ...

And we can import and show the final metadata in the Taginfo  /  OSM wiki / other tools

But merging is not easy, not a simple 1:1 relationships.

**Comment by matkoniecz** [comment]
> A number of tag infoboxes at the OSM Wiki link to a corresponding Wikidata entity

And this links are often not linking to actually matching terms.

Also, what would be use of displaying this data (except promoting Wikidata)?

**Comment by drmx** [comment]
Hello! The Wiki {{Key/ValueDescription}} templates allows to display a tag information box on the wiki. If the template has no parameters then the wiki shows full info from the wikidata, but Taginfo doesn't show anything.
It would be cool if Taginfo could show in the same way. If there are options in the Wiki then display this data, otherwise display data from Wikidata. This way we won't have different descriptions in different places.

**Comment by matkoniecz** [comment]
See also https://wiki.openstreetmap.org/wiki/Proposed_features/remove_link_to_Wikidata_from_infoboxes - infoboxes are no longer displaying this.

**Comment by joto** [comment]
As @matkoniecz says this was removed from the Wiki because it isn't that useful. Closing here.
