### ISSUE TITLE
Links in wiki description look strange in taginfo docs

### ISSUE THREAD

**Issue by bhousel** [taginfo/taginfo#225]
Somebody put a link into the description on the [`healthcare=laboratory` wiki page](https://wiki.openstreetmap.org/wiki/Tag:healthcare=laboratory)

<img width="253" alt="screenshot 2018-04-10 16 59 33" src="https://user-images.githubusercontent.com/38784/38583318-a0d13d26-3ce0-11e8-89b3-155a31085966.png">

The link gets expanded into `en=Medical_laboratory=` and it looks weird in iD.

<img width="864" alt="screenshot 2018-04-10 16 59 39" src="https://user-images.githubusercontent.com/38784/38583323-a3df8c48-3ce0-11e8-87e3-46f7dff759e0.png">

<img width="375" alt="screenshot 2018-04-10 16 59 49" src="https://user-images.githubusercontent.com/38784/38583329-a6e9fafe-3ce0-11e8-9d49-769bbe529403.png">

This seems kind of related to #199 (`=` in description causes problems).  Maybe it's possible to sanitize the description, turning it into just plaintext.

**Comment by joto** [comment]
Sanitizing this would mean parsing the horrible Mediawiki syntax even more. I don't think this is an option. Descriptions should not contain links.
