### ISSUE TITLE
Colon (":") character inside osm keys

### ISSUE THREAD

**Issue by ImreSamu** [taginfo/taginfo#235]
I have tested the current master ( Latest commit ffafd73 )  
-  ( with "bundle install"  patch  -> `sinatra (2.0.3)`  )

And I have a small problem with
-  Colon (":") character inside osm keys  [ `addr:street` ; `addr:city` ...]

my guess:  
* something  changed  inside  the `sinatra 2.x.x`

example: 
* my local test url : http://127.0.0.1:30002/keys/addr%3Astreet 
* current live system : https://taginfo.openstreetmap.org/keys/addr%3Astreet

## Now I get - http://127.0.0.1:30002/keys/addr%3Astreet 

![screenshot from 2018-07-04 02-10-51](https://user-images.githubusercontent.com/2217320/42250289-4f72f806-7f30-11e8-8ed1-bcb4d6f47685.png)

## Expected:

![screenshot from 2018-07-04 02-17-56](https://user-images.githubusercontent.com/2217320/42250318-84c72c02-7f30-11e8-9e4c-cbb3b92fa853.png)

**Comment by joto** [comment]
I can confirm this in my test setup using Webrick. The main taginfo site uses Apache/passenger and there it doesn't show.

I guess something changed in Ruby, Webbrick, Rack, and/or Sinatra that it isn't doing a proper URLdecoding any more. No idea where to start finding this.

What web server are you using @ImreSamu ?

**Comment by ImreSamu** [comment]
>The main taginfo site uses Apache/passenger and there it doesn't show.

I see - https://taginfo.openstreetmap.org/taginfo  is up-to-date  - and no problem. [ `Software Version  2018-07-03T21:00:14Z (ffafd73388)` ]


>What web server are you using

A simple minimal  `./taginfo.rb 4567`
 
I prefer a minimal memory usage per taginfo service ( in my https://github.com/taginfo/dockerized-taginfo project )   
I am running hundreds of taginfo web services parallel -  so every Mb is important.


>I guess something changed in Ruby, Webbrick, Rack, and/or Sinatra   ...

with older gem versions - it is working - my settings:
```bash
        && gem install rack          --clear-sources --no-document  -v '<2.0.0' \
        && gem install rack-contrib  --clear-sources --no-document  -v '<2.0.0' \
        && gem install sinatra       --clear-sources --no-document  -v '<2.0.0' \
        && gem install sinatra-r18n  --clear-sources --no-document \
        && gem install json          --clear-sources --no-document \
        && gem install sqlite3       --clear-sources --no-document \
```

> No idea where to start finding this.

As I see - this is not a critical issue 
- the main taginfo website is working  :)
- and I have a workaround (  -v   '<2.0.0'  )

**Comment by ImreSamu** [comment]
### PUMA  ( A Ruby/Rack web server ) test

gem files

```
 && gem install rack          --clear-sources --no-document \
 && gem install rack-contrib  --clear-sources --no-document \
 && gem install sinatra       --clear-sources --no-document \
 && gem install sinatra-r18n  --clear-sources --no-document \
 && gem install json          --clear-sources --no-document \
 && gem install sqlite3       --clear-sources --no-document \
 && gem install puma          --clear-sources --no-document \
```

start: `ruby ./taginfo.rb 4567 -s Puma`
* based on puma docs: https://github.com/puma/puma#sinatra

logs:
```
taginfo-zz-ni_1     | /osm/taginfo/web/lib/utils.rb:6: warning: constant ::Fixnum is deprecated
taginfo-zz-ni_1     | Puma starting in single mode...
taginfo-zz-ni_1     | * Version 3.11.4 (ruby 2.6.0-p-1), codename: Love Song
taginfo-zz-ni_1     | * Min threads: 0, max threads: 16
taginfo-zz-ni_1     | * Environment: development
taginfo-zz-ni_1     | * Listening on tcp://0.0.0.0:4567
taginfo-zz-ni_1     | Use Ctrl-C to stop
taginfo-zz-ni_1     | == Sinatra (v2.0.3) has taken the stage on 4567 for production with backup from Puma
```

tested and replicated with Puma + **Sinatra (v2.0.3)** with different ruby versions

|docker official image     | puma and ruby version                 | test result           |
|--------------------------| --------------------------------------| ----------------------|
|ruby:2.6.0-preview2-alpine3.7 | `Version 3.11.4 (ruby 2.6.0-p-1)` | colon problem replicated |
|ruby:2.5-alpine3.7 | `Version 3.11.4 (ruby 2.5.1-p57)`  | colon problem replicated |
|ruby:2.4-alpine3.7 | `Version 3.11.4 (ruby 2.4.4-p296)` | colon problem replicated |

**Comment by ImreSamu** [comment]
###  Nginx/Phusion Passenger 5

I have replicated "the colon problem" with
* official [phusion/passenger-ruby25](https://hub.docker.com/r/phusion/passenger-ruby25/) docker image +   `bundle install`  ( sinatra (2.0.3)  )

it is a "Nginx" webserver + "Phusion Passenger 5" preconfigured image 
*  doc: https://github.com/phusion/passenger-docker

```log
taginfo-zz-ni_1     | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
taginfo-zz-ni_1     | *** Running /etc/my_init.d/10_syslog-ng.init...
taginfo-zz-ni_1     | Jul  4 15:16:37 f4709f4a966d syslog-ng[201]: syslog-ng starting up; version='3.5.6'
taginfo-zz-ni_1     | Jul  4 15:16:38 f4709f4a966d syslog-ng[201]: EOF on control channel, closing connection;
taginfo-zz-ni_1     | *** Running /etc/my_init.d/30_presetup_nginx.sh...
taginfo-zz-ni_1     | *** Running /etc/rc.local...
taginfo-zz-ni_1     | *** Booting runit daemon...
taginfo-zz-ni_1     | *** Runit started as PID 208
taginfo-zz-ni_1     | Jul  4 15:16:38 f4709f4a966d cron[215]: (CRON) INFO (pidfile fd = 3)
taginfo-zz-ni_1     | Jul  4 15:16:38 f4709f4a966d cron[215]: (CRON) INFO (Running @reboot jobs)
taginfo-zz-ni_1     | ok: run: /etc/service/nginx-log-forwarder: (pid 214) 0s
taginfo-zz-ni_1     | [ N 2018-07-04 15:16:38.2828 217/T1 age/Wat/WatchdogMain.cpp:1297 ]: Starting Passenger watchdog...
taginfo-zz-ni_1     | [ N 2018-07-04 15:16:38.3074 220/T1 age/Cor/CoreMain.cpp:1202 ]: Starting Passenger core...
taginfo-zz-ni_1     | [ N 2018-07-04 15:16:38.3076 220/T1 age/Cor/CoreMain.cpp:252 ]: Passenger core running in multi-application mode.
taginfo-zz-ni_1     | [ N 2018-07-04 15:16:38.3185 220/T1 age/Cor/CoreMain.cpp:937 ]: Passenger core online, PID 220
taginfo-zz-ni_1     | [ N 2018-07-04 15:16:40.5784 220/T5 age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
taginfo-zz-ni_1     | Jul  4 15:17:01 f4709f4a966d CRON[247]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
...
```

**Comment by ImreSamu** [comment]
probably this issue  is related to : https://github.com/sinatra/sinatra/issues/1443  and maybe a simple  `unescape()`  problem.

I have tested the fix - and it is working for me.  :+1: 
```
        && gem install rack          --clear-sources --no-document \
        && gem install rack-contrib  --clear-sources --no-document \
        && gem install specific_install --clear-sources --no-document \
        && gem specific_install -l https://github.com/jkowens/sinatra.git -b fix-1443 \
        && gem install sinatra-r18n  --clear-sources --no-document \
        && gem install json          --clear-sources --no-document \
        && gem install sqlite3       --clear-sources --no-document \
```

**Comment by joto** [comment]
Thanks @ImreSamu for your extensive analysis. Looks like this will be in the next release, so I'll keep this issue open for the time being but don't think we'll do anything for the time being.

But it is strange that nobody noticed this in over a year that version 2 of Sinatra was out...

**Comment by ImreSamu** [comment]
> but don't think we'll do anything for the time being.

the suggested gem installation - with `bundle install` - using `Sinatra 2.0.3`
*    ( https://github.com/taginfo/taginfo/blob/master/Gemfile.lock )

Maybe reverting the `bundle install`   to `Sinatra 1.4.8` is useful.  
The official OSM chef is now using this : [openstreetmap/chef:"Use bundler to install gems for taginfo"](https://github.com/openstreetmap/chef/commit/f3613eb42ce4127a2b2ceed8d835ff4a3cd97978)

**Comment by ImreSamu** [comment]
Sinatra 2.0.4 release is solved this problem.
