### ISSUE TITLE
RTL display

### ISSUE THREAD

**Issue by iriman** [taginfo/taginfo#236]
Hi, I tried to prepare a minimum required rules for a better rtl display.
* There are some new additions, some changes to values or attributes of css rules. 
* In addition to 'taginfo.css' there are few overwrites to the rules of other css files.
* Since the flexigrid tables most of the time contain some Latin strings, it's better to keep them LTR. There is an exception to this when we have RTL descriptions and then we should give the correct direction only to that column. For now it's good.
* Also there is a change to the font. 'Noto Sans Arabic UI' web font or at least 'Tahoma'.
* I tested this css using Fiddler software and almost everything major seems to be good.
**Download**: [taginfo - rtl.zip](https://github.com/taginfo/taginfo/files/2164031/taginfo.-.rtl.zip)

![main-after](https://user-images.githubusercontent.com/8467903/42289898-887a1f74-7fd7-11e8-8915-a98b373e0cc2.png)
![tags-after](https://user-images.githubusercontent.com/8467903/42289901-88ee1d8e-7fd7-11e8-89c7-256eaee7ff09.png)

**Comment by joto** [comment]
Thanks for trying this out. Bringing this into taginfo will be a bit more complex:

1. All `text-align`, `float` and `clear` CSS settings can be set to special values that work for LTR and RTL texts. Maybe there are other settings we can make more generic.
2. Everything else that's different should go into a different CSS file. So we'd have one CSS file that is always the same, and an extra CSS file for LTR and one for RTL languages.
3. I need to figure out a way to include the correct CSS file in addition to the common one.

I think this is probably the cleanest approach and reasonably easy to maintain.

If you can supply 1 and 2, I'll work on 3.

**Comment by joto** [comment]
I looked into this some more and there are some problems. The way this is supposed to work is not to change all the CSS, but to add a `dir="rtl"` to the `html` element. I tried this, and presto, most of the stuff is switched. So this is going in the right direction. This approach has the advantage that adding the direction marker to the page is trivial and we don't need to swap out any CSS.

There is some problem with some parts of the site which have `position: absolute`, but they can either be converted to `position: relative` or CSS rules with `html[dir="rtl"]` can be added, so that they are only used when this is an RTL language. I fiddled around with this a bit and I think this is doable. It is made more difficult by the page changing layout when the screen is smaller (like on a smart phone), so this needs a lot of testing.

But there is currently one thing I don't have any idea how to fix: The `tipsy` jQuery plugin used for the tool tips can't hande the RTL pages, it positions the tool tips at the wrong location (often off screen). I can switch off use the of `tipsy` completely for RTL languages, but maybe there is a better solution.

@iriman Maybe you want to play around with this a bit and see if you can find some solutions.

Here is some background:
* https://hacks.mozilla.org/2015/10/building-rtl-aware-web-apps-websites-part-2/
* https://alfy.me/2014/07/26/lets-talk-about-rtl.html)

**Comment by iriman** [comment]
Thanks, the links were so informative.

- I added `dir="rtl"` and then updated the 'taginfo.css' using the `html[dir="rtl"]` selector:
[taginfo-new.zip](https://github.com/taginfo/taginfo/files/2175403/taginfo-new.zip)
- There is a change to the `footer_left` and `footer_right` CSS rules. I think it can be used in LTR mode , too.
- About 'tipsy', I googled and found [this](https://phabricator.wikimedia.org/T69506):

    > there is a $.fn.tipsy.autoBounds function (it needs to be passed as gravity option to tipsy() function) which changes the tooltip gravity depending on how far it is from the document edge

hope it help.
- Again, I added some additional rules for rtl mode: 1 for 'slicknav.min.css', 3 for 'comparison page', 3 for 'jquery-ui-1.8.10.custom-minified.css', 1 to override an inline css and some rules to keep some parts ltr.
- 'flexigrid' tables are kept LTR since imo this way it's more readable, because they mostly contain LTR contents. There are some exceptions like 'value' column when it contains RTL names, 'description' column or maybe some others. I think later we can use some scripts to switch between rtl and ltr direction for those columns automatically, something like `dir=auto`. We can use this way for `#pre-text` text too, so the text will flow in the correct direction if a translation is not available for it.
- 'overview' tab, chart 'canvases' and 'input fields' are some other parts I kept them LTR.
- 'API documentation' will get rtl direction by default. If we have a class for it, then we can make it ltr.

**Comment by joto** [comment]
I have added you CSS with minor changes. Thank you!

* I fixed the API documentation page.
* One little change was needed and all the tipsy stuff seems to work now, but I haven't checked everything. If you see one that doesn't work correctly, let me know.

I think this looks really good now. There is one thing I am not 100% happy with: Tables and canvas appear flushed to the left while, for instance, the title and text above the table is flush to the right. This doesn't matter much if your screen isn't too wide, but if it is, it looks odd. See this Screenshot:

![screenshot-taginfo-farsi](https://user-images.githubusercontent.com/113756/42728648-5709472c-87bf-11e8-8613-069a6fded4da.png)

Maybe it would be better if the table is at the right (but still oriented ltr internally)?

(There is also something wrong with the "dot" in the marked position.)

**Comment by iriman** [comment]
Great! thanks.

* At the first look, table alignment was a bit strange for me, too, specially on 'similar' tab in which the table is less wide, but after a while I got used to it.

  I think if we flush it to the right it will make some confusions. For example when someone tries to resize columns. In ltr mode we drag from left to right, while from right to left in rtl mode.  Confusion is here: when the table is aligned at the right side I expect a rtl table (specially here that all other things have got rtl direction, so I'll think it is like others but it's ltr), so if I want to widen a column, I'll try to drag the column handle to the left (my assumption) while I should drag it to the right (it's ltr), and then if I do the correct movement the table will expand to the left while I expect right. Also someone may need to wait and look a bit to find out that the table starts from left side not right. 

  Imo if we put it at right side then should make the whole table rtl, and as I see it needs more work than others to all parts of the table do the right thing.

* In this matter I see no problem with canvases. I think we can do it.

* for the text above table and that dot I think we can do one of these two:
  * check if the wiki text is translated or not: if it isn't a translated version then we should apply `direction:ltr` to it. Here building key is not translated and original English text is returned, so I'm not sure is it possible to apply a html/css directional rule using this condition?
  * using some scripts to simulate `dir=auto`, like [this](http://jsfiddle.net/Hcx6H/436/).

* a problem still exists with tipsy tooltip here (hover cursor over highlighted text):
![hover](https://user-images.githubusercontent.com/8467903/42763050-32c1487e-8927-11e8-8d7f-207d8976bd5a.png)

**Comment by joto** [comment]
I added `lang` and `dir` tags to some of the texts coming from the wiki. This includes the description text mentioned above and the texts in the "wiki" tab of a key/tag/relation. I also fixed the tooltip you found.

btw: What do the `/*?*/` comments mean in the CSS file you sent me?

**Comment by iriman** [comment]
I wasn't sure what those rules do, then put comment for my reference. you may remove them.

**Comment by iriman** [comment]
thanks, all are working good, but description text in the 'values' tab isn't affected by this change. for example see the description of 'service' in the 'values' tab of 'highway' key.

**Comment by joto** [comment]
I fixed the description in the values tab also.

**Comment by joto** [comment]
Looks like everything is done here, so I am closing this. Everybody: Feel free to open new issues if you see places where RTL/LTR isn't done properly. I am sure there are still some pages that could be improved.
