### ISSUE TITLE
Thin space separator between digits in RTL context

### ISSUE THREAD

**Issue by iriman** [taginfo/taginfo#237]
## Problem
In right-to-left context, numbers will be reversed by each grouped digits that are separated with Thin Space. (Numbers that are sorrounded by RTL scripts, like Persian)

**Default behavior with LTR scripts:**
![22](https://user-images.githubusercontent.com/8467903/42300627-a0d6796a-8026-11e8-8988-ce605b88b65d.png)

**RTL script and Thin Space:**
Numbers in the table are in LTR mode and have no problem with thin space.
But when the number appears in RTL context (as in the line bellow the table) it will be reversed by its grouped digits.
![11](https://user-images.githubusercontent.com/8467903/42300626-a09a8b9e-8026-11e8-90ef-8c9ffde0817c.png)

## Solutions I found:
I'm not sure which one is the best and has most compatibility with browsers. I prefer first one because it's common and simple.

1. **Using No-Break Space (U+00A0) instead of Thin Space (U+2009)**
![33](https://user-images.githubusercontent.com/8467903/42300628-a112db3a-8026-11e8-91cf-5de63e69764d.png)

2. **Wrapping numbers in a LTR block:**
![44](https://user-images.githubusercontent.com/8467903/42301269-98eb494e-8029-11e8-878e-7af008120b59.png)

**Comment by joto** [comment]
Is this still a problem after all our changes?

**Comment by iriman** [comment]
yes, the example above still exsits.
for the first solution I searched a bit and found out that unicode standard on page 234 [says](http://www.unicode.org/versions/Unicode11.0.0/ch06.pdf):

> U+00A0 no-break space behaves as a numeric separator for the purposes
> of bidirectional layout. 

also there is a narrow version of it:

> U+202F narrow no-break space (NNBSP) is a narrow version
> of U+00A0 no-break space

**Comment by joto** [comment]
Should be fixed now.

**Comment by iriman** [comment]
yes, thanks.
