### ISSUE TITLE
Taginfo doesn't find all values that include search term

### ISSUE THREAD

**Issue by SelfishSeahorse** [taginfo/taginfo#243]
Taginfo finds all keys that include the search term, but it doesn't find all values that include the search term (it seems that it only finds values where the search term is surrounded by spaces or underlines).

For example, entering `flower`, Taginfo finds the key `flowerbed`, but it doesn't find the value `flowerbed` (it only finds the values `Flower`, `Flower Street`, `flower_bed`, ...).

**Comment by joto** [comment]
This is intended behaviour. Doing a real substring query would be too slow with the nearly 100 million distinct tags that we have.

**Comment by SelfishSeahorse** [comment]
OK, that seems reasonable.
