### ISSUE TITLE
bring cursor automatic to search box after opening https://taginfo.openstreetmap.org/ webpage

### ISSUE THREAD

**Issue by my-na-me** [taginfo/taginfo#245]
Thank you for the great tool.

There is a minor feature request. I would like to see a comfortable behavior after opening https://taginfo.openstreetmap.org/ webpage:
The cursor should jump into the search box, so that the user can start typing characters instantly , (for instance similar like webpage https://duckduckgo.com/ is providing this).
Is this function currently implemented & I'm just doing a unfavorable use of the webpage, or maybe there is a wrong browser setting on my machine?

Thanks for reading.

**Comment by joto** [comment]
The taginfo site supports several shortcut keys (type `?` to get a list), you can use `s` to activate the search box. Activating the search box automatically would break these shortcuts.

**Comment by joto** [comment]
Shortcut keys are discoverable and new visitors will also not expect the search box to necessarily have automatic focus. Either behaviour makes sense I guess. But the current one has been around for many years, so I don't think I will break that.

**Comment by my-na-me** [comment]
Thank for information.
Actually, I didn't found link to keyboard shortkeys page control (https://taginfo.openstreetmap.org/help/keyboard) - Could you put a link for it on main-page?

**Comment by joto** [comment]
There is a link called "Help" on all the taginfo pages including the main page.

**Comment by my-na-me** [comment]
As you explain here:
https://github.com/taginfo/taginfo/issues/245#issuecomment-409571108
"The taginfo site supports several shortcut keys (type "?" to get a list), you can use "s" to activate the search box. Activating the search box automatically would break these shortcuts."

In meanwhile the activation for the search box using the "s"-key works well for me. But unfortunately the "s"-key does not only provide the action of activating the search-box, there is an another action happened at the same time, that the letter/character  "s" will also inserted into the search-box.

If you want search strings which starts with "s", then you have an advantage and you can straight away typing the rest of the search-string, but most of the search-string don't start with letter "s" and you have to remove at "s" which is always there.

So, could you change this behavior. I expect when hitting the "s" key, the search-box is activated only, but without inserting character "s" into the activated search-box. 

PS: Should I better open a new issue-ticket for this [request?

**Comment by joto** [comment]
Yes, you should open new issues for new things.
