### ISSUE TITLE
report:"Wiki images" ->  "Internal Server Error"

### ISSUE THREAD

**Issue by ImreSamu** [taginfo/taginfo#249]
https://taginfo.openstreetmap.org/reports/wiki_images -> "Internal Server Error"

steps to reproduce:
* https://taginfo.openstreetmap.org/reports
* select "Wiki images" -> https://taginfo.openstreetmap.org/reports/wiki_images 
  *  ->  **"Internal Server Error"**

**Comment by joto** [comment]
Turns out it was just a broken image in the wiki. I have fixed this, instead of the image the text "Broken image" will appear in the report.
