### ISSUE TITLE
'null' description for highway=construction

### ISSUE THREAD

**Issue by lonvia** [taginfo/taginfo#255]
In the [list of highway values](https://taginfo.openstreetmap.org/keys/highway#values) (second page) the description for 'construction' is listed as 'null'. The page itself says that it has no description.

Another 'null' appears in the [description page](https://taginfo.openstreetmap.org/tags/highway=construction#wiki) for Brazilian Portuguese (pt-br).

**Comment by matkoniecz** [comment]
It is not surprising - see https://wiki.openstreetmap.org/w/index.php?title=Tag:highway%3Dconstruction&redirect=no

It has no description.

**Comment by lonvia** [comment]
Sure. To clarify: the ticket is about taginfo printing 'null' in this case instead of just leaving the description empty.
