### ISSUE TITLE
Feature Request- get wiki description from redirected page

### ISSUE THREAD

**Issue by dieterdreist** [taginfo/taginfo#256]
it would be nice to see a definition from the redirected page. If the tag definition redirects to a proposal, the definition of the proposed tag could be shown. If there are several proposals for the same tag, the tag definition page could become a disambiguation page (essentially point to the different proposals) and no definition would be shown in taginfo (no redirect in the wiki).

**Comment by joto** [comment]
Don't use redirects for tags, they are confusing as hell. And understanding proposals is out of scope for taginfo.
