### ISSUE TITLE
remove letter "s" form search-box after activation search-box by hitting shortcut-key "s"

### ISSUE THREAD

**Issue by my-na-me** [taginfo/taginfo#258]
As mentioned here:
https://github.com/taginfo/taginfo/issues/245#issuecomment-476604177
and requested here:
https://github.com/taginfo/taginfo/issues/245#issuecomment-476695853
I add this new ticket.

Please don't put letter "s" into the search-box, then you just want to get the focus of this box when hitting shortcut-key "s"

**Comment by joto** [comment]
I can not reproduce this, it works well for me. What browser etc. are you using?

**Comment by my-na-me** [comment]
Interesting.
I'm using different browsers, like Chrome / Firefox / Brave / IE v11 (win7 64b),
Firefox is OK
For Chrome / Brave  / IE v11 i can see this behavior, typing "s" then the search box is activated and character "s" will be inserted into the box at same time, see here:
.
screenshot-version:
![chrome version](https://user-images.githubusercontent.com/27923772/55365425-d2f41900-54e4-11e9-855c-e8c6da832292.png)
.
.
behavior:
![taginfo s](https://user-images.githubusercontent.com/27923772/55365232-0d10eb00-54e4-11e9-987c-493f9018bdfc.gif)

**Comment by joto** [comment]
There was a difference in event handling in Firefox vs. Chrome. This should work now as intended. Thanks for the report.

**Comment by my-na-me** [comment]
Thanks for fixing :-)
