### ISSUE TITLE
Wrong stat for a tag

### ISSUE THREAD

**Issue by nlehuby** [taginfo/taginfo#259]
I have spotted some case where the overview stats do no match the OSM database:

tag amenity=bus_station, France instance
Taginfo says 3 ways
`https://taginfo.openstreetmap.fr/tags/amenity=bus_station`

Overpass says 383 ways
`http://overpass-api.de/api/interpreter?data=[out:json][timeout:325];area(3601403916)->.searchArea;(nwr["amenity"="bus_station"](area.searchArea););out count;`

I'm not sure if the areas used for this Overpass request and for Taginfo French instance are exactly the same ones, but even for one French Region, I have more than 3 ways...

**Comment by nlehuby** [comment]
Here is another one:
https://taginfo.openstreetmap.fr/tags/amenity=car_pooling 
Total - 87
Nodes - 87

Overpass:
total : 130
nodes : 94
ways : 36

**Comment by joto** [comment]
Please take this up with the owner of the France instance.
