### ISSUE TITLE
web request fail with 'NoMethodError - undefined method `sub' for nil:NilClass:'

### ISSUE THREAD

**Issue by Marc-marc-marc** [taginfo/taginfo#261]
after an update, web request fail, log is

> 2019-04-11 13:22:43 - NoMethodError - undefined method `sub' for nil:NilClass:
> 	./taginfo.rb:131:in `block in <class:Taginfo>'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:983:in `block in filter!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:983:in `each'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:983:in `filter!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1096:in `block in dispatch!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
> 	/var/lib/gems/2.3.0/gems/rack-contrib-2.1.0/lib/rack/contrib/jsonp.rb:37:in `call'
> 	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'
> 	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
> 	/var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
> 	/var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
> 	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
> 	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
> 	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by lonvia** [comment]
Is that about the French instance of taginfo again? Then you rather should report this to the sysadmins of openstreetmap.fr.

**Comment by Marc-marc-marc** [comment]
> Is that about the French instance of taginfo again?

yes indeed, an update of the French instance was made following the problem #259 since the other instances don't seem to have the bug

> Then you rather should report this to the sysadmins of openstreetmap.fr

Ok
