### ISSUE TITLE
Display Wikidata labels

### ISSUE THREAD

**Issue by pigsonthewing** [taginfo/taginfo#262]
For Taginfo pages for values that include a Wikidata component, in either of these forms:

https://taginfo.openstreetmap.org/tags/wikidata=Q2191338

https://taginfo.openstreetmap.org/tags/manufacturer%3Awikidata=Q2372128

(for any type of key:wikidata= )

Please fetch and display the label (and description) of the Wikidata item, and display a link to the item. for the former, either use English or the user's preferred language if known; taking advantage of Wikidata's "Language fall-back" if the first preference is not available.

Note that there are already or two million objects with Wikidata values:

https://taginfo.openstreetmap.org/keys/wikidata

Additionally it would be good to display labels on the above page.

**Comment by mmd-osm** [comment]
I think that's probably something where @nyurik and his OSM Sophox Service on https://sophox.org would be the best bet.

**Comment by pigsonthewing** [comment]
For a use case where the latter change would be very benefcial, see my email at:

https://lists.openstreetmap.org/pipermail/talk/2019-April/082427.html

**Comment by joto** [comment]
Taginfo is a general tool, it tries very hard not to give special meaning to some tags. It treats all tag keys and values just as strings. For instance the pages for the `website` key doesn't give you links to the values. I am sure there are cases where this would be useful, too. You should probably write your own tool (possibly using the taginfo API) if you want to apply special meaning to tags.

**Comment by pigsonthewing** [comment]
Thank you for the suggestion. I do not wish "to apply special meaning to tags".

I wish TagInfo to expose the meaning that is _already in the tags_, but is encoded using _identifiers explicitly intended for machines_, by exposing the associated text labels that are _explicitly intended for humans_.

I would be very surprised if there is any user of TagInfo who can say what something like https://taginfo.openstreetmap.org/tags/wikidata=Q2191338 refers to, without manually copying and pasting the "Q2191338" value into Wikidata (or some third-party tool that accesses Wikidata). Why should any human have to do that, when we have machines to do it for us?

**Comment by joto** [comment]
All tags in OSM have special meaning, there is nothing special about wikidata tags in that respect. And, as explained, taginfo is trying to be "meaning-neutral". It doesn't interpret what something is. Taginfo doesn't decide that a key of a certain format means that the value for that key must be a wikidata item just as it doesn't decide that the value for a "highway" key must be from a certain list. Taginfo is not the tool you are looking for.
