### ISSUE TITLE
Add link to Wikibase / Data item

### ISSUE THREAD

**Issue by tordans** [taginfo/taginfo#263]
There are tags like `barrier_1=gate` that don't have an OSM-Wiki page, not even a redirect. That makes sense IMO, since they are really just an editing error.

However, there are OSM-Wikibase-Data items for them, which is great, since this is IMO a great place to inform users that this is not a desired tag – in this case.

Suggestion:
On the "Wiki"-Tab, add a second links to the OSM-Data item for the given tag.

Example: 
- https://taginfo.openstreetmap.org/tags/barrier_1=gate#wiki
- https://wiki.openstreetmap.org/wiki/Item:Q8979

--- 

A bit related but something different: https://github.com/taginfo/taginfo/issues/248.

PS, there are other open Wikidata issues here ([Github Search](https://github.com/taginfo/taginfo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+wikidata)) but as far as I understand it, they are about "external" Wikidata, not the OSM-Data item, right?

**Comment by joto** [comment]
Sorry, I don't understand what you want here and I don't understand what https://wiki.openstreetmap.org/wiki/Item:Q8979 is supposed to be. Adding wiki pages for all tags that should NOT exist seems rather strange to me.

**Comment by tordans** [comment]
> (…) I don't understand what https://wiki.openstreetmap.org/wiki/Item:Q8979 is supposed to be. Adding wiki pages for all tags that should NOT exist seems rather strange to me.

@nyurik will be able to explain this better than me.

The way I understand it is:
Every Tag in Taginfo (with a threshold(?)) is a OSM-Data item.
The Data item does not require a Wiki page. But if there is a OSM Wiki page for this tag, the Data item and Wiki page are linked (via a Bot or manually).
The Data item allows us to add structured data to OSM-Keys and OSM-Tags – more about this at https://wiki.openstreetmap.org/wiki/Data_items.

It also allows us to describe a tag with minimal effort and minimal information, in cases when a whole OSM-Wiki page is too much.

For the specific `barrier_1`-key: The data item could (in this case should?) inform users, that this tag is a typo (?) of the `barrier`-key and should not be used.
Which is way more helpful than having NULL information. 
For example in iD, it will show the Data item description: 
<img width="354" alt="Bildschirmfoto 2019-05-18 um 22 22 37" src="https://user-images.githubusercontent.com/111561/57974685-a58ffb80-79bc-11e9-93f3-8aad82f72fb0.png">

> Sorry, I don't understand what you want here 

I suggest to extend the "wiki" page with a second section, which links to the OSM-Data item.

This section could do more than just link, but IMO having the link would be a great first step.

_Wireframe:_
<img width="792" alt="Bildschirmfoto 2019-05-18 um 22 35 59" src="https://user-images.githubusercontent.com/111561/57974745-83e34400-79bd-11e9-9ad8-929641c3b5ac.png">

This section will be especially helpful for taginfo-pages that don't have a OSM-Wiki page since the Data item will likely have some information.

AFAIK, iD does pull the Data item info via JS on demand. So possibly this section could only show up if such a API request has a proper result.

--- 

Note: AFAIK, right now there is no way to add OSM-Data items manually. They are added by a bot based on usage (base don taginfo, AFAIK). Therefore the Wireframe above does not have an "add"-Link. But this might be one of the thinks that could be interesting to explore later.

**Comment by nyurik** [comment]
@tordans, thanks for a great description!

@joto, data items reflect the keys, values, relations, and roles that exist in the OSM data. Data items make it very easy to add a short one-line description to any of them, in any language, without the need to create a full wiki page and deal with wiki markup. iD already uses this information directly.

https://wiki.openstreetmap.org/wiki/Item:Q8979 is a `barrier_1` key. It exists because OSM data has 300+ instances of that key.  Bot auto-created it, and later a user added some descriptive text. We currently have 50+ users contributing these descriptions, often for keys/values/roles/relations that have no wiki pages.

**Comment by joto** [comment]
It doesn't make sense to me to document broken tags, it doesn't scale. Just fix the tags and be done with it. For the rest we already have #248, right?

**Comment by tordans** [comment]
> It doesn't make sense to me to document broken tags, …

To me it does.
It is a completely different message to me and especially a new mapper to see a tag and know that it is broken.

Example: How would a novice mapper find out, that the *_1 pattern is really a bug, not a feature. Only by time consuming research. With this, its just one click in iD. This issue is about having the same ease and clarity in taginfo.

The information "no info" does not say "no info 'cause no one added it, yet" vs. "no info, because we don't want this tag". The only smart info for a tag we don't want is to say so.

> …it doesn't scale.

This problem is solved already. It's already scaling. The tags are created. The descriptions are added by the OSM wiki community. 

In which way does it not scale? And what is the worst that could happen for taginfo? If a Data item is not documented, it would say so; which is the same it does today.

> Just fix the tags and be done with it.

Example: There are over 800k `name_1` keys https://taginfo.openstreetmap.org/search?q=_1. And even more other tags that are likely "bugs". Those cannot be "fixed and be done with it". Those need to be looked at by a mapper. Which is why it is a good idea to have a description for them.

> For the rest we already have #248, right?

I agree, this issue might be a duplicate in the way, that in #248 all places that talk about the description of a tag should change its source to use the Data item. And this issue is only talking about the wiki-page specifically. If it's helpful, let's move the talk over to the other issue.

**Comment by bhousel** [comment]
> Example: How would a novice mapper find out, that the *_1 pattern is really a bug, not a feature. Only by time consuming research. With this, its just one click in iD. This issue is about having the same ease and clarity in taginfo.

Just wanted to point out that iD would only ever show a tag like this in the raw tag editor, and anyone using that is really not a novice.  

Also look.. many iD users are not novices.  I really hate that people perpetuate this myth.  Yes, we want novices to feel welcome using iD so they will stick around, and I want them taken care of first, but today there are thousands of professional mappers using the software too.

I think anyone working directly with raw OSM tags should mostly be able to figure out for themselves how the tags work, and we shouldn't expect documentation for every made-up or temporary thing.  

> This problem is solved already. It's already scaling. The tags are created. The descriptions are added by the OSM wiki community.

This is... really not happening consistently, at least from my view of things.

I wrote [this in 2016](https://github.com/openstreetmap/iD/issues/2896#issuecomment-169522509):

For me personally, OSM got a lot easier to deal with once I embraced the idea that it's a big messy ball of mud and people are free to add whatever nonsense they want to it.

Maybe someone can write a bot to update all the `xxx_#` wikibase pages to say:  "At the time the feature was created, the mapper - or script - was not sure exactly which value to choose, so they added `xxx_#` as a less preferred alternative value.  If you don't find this tag useful, and you have knowledge that the feature is tagged correctly, feel free to delete the `xxx_#` tag."

**Comment by pyrog** [comment]
>Adding wiki pages for all tags that should NOT exist seems rather strange to me.

We don't want to add wiki pages for all tags (at all 😉 ).
In the wiki, we have a similar concept with `{{PossibleSynonym}}` template.

See [Key:bridge#Possible synonym](https://wiki.openstreetmap.org/wiki/Key:bridge#Possible_synonym)

**Comment by pyrog** [comment]
https://github.com/taginfo/taginfo/issues/248#issuecomment-424834182

>There has been some concerns by the community with regards to more advanced usage of the new system, e.g. using it for presets, **validation rules**, but otherwise it had high level of support.

A lot of values or sub tags don't need to have their own wiki page, but they have already a Data item.

The OSM Wikibase is the place to store and share the knowledge about OSM keys and tags.

**Comment by pyrog** [comment]
> It doesn't make sense to me to document broken tags

This is a particular case.

More generally a lot of valid and used tags don't have any wiki pages. But they have their Data Item.
So displaying their label, description and aliases in the user language will be useful.

**Comment by joto** [comment]
Closing as wont fix. It seems to me, wikibase was a failed experiment which didn't get enough mind share.

**Comment by 1ec5** [comment]
FYI, there’s [a relevant discussion](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Redundant_pages_for_%22building_block%22_tags) about whether the wiki should strive to document compound keys using individual wiki pages that taginfo scrapes or whether such pages should be omitted in favor of data items.

**Comment by matkoniecz** [comment]
> Closing as wont fix. It seems to me, wikibase was a failed experiment which didn't get enough mind share.

Then "Use Wikibase data instead of parsing wiki text" likely #248 also should be closed

**Comment by cuatim** [comment]
Hi, I think this issue and #248 should be re-opened. Wikibase is here to stay.

Official statement:

> The Wikibase is now widely used and while we still have issues with it, it is being supported.

-- https://github.com/openstreetmap/operations/issues/764#issuecomment-4012425209

**Comment by WKobes** [comment]
@joto Can you consider re-opening this issue? I think the argument in this issue was focused on nonsense keys like barrier_1. Indeed,  we do not need OSMWiki data items for every key/tag combination out there. Yet, I would really benefit from a link on the Wiki tab to the Data Item for regular keys and tags (could be somewhat like done in https://github.com/taginfo/taginfo/issues/263#issuecomment-493706043, but wouldn't mind if the data item link would be made smaller/less prominent).

I would use this to quickly navigate between Wikidata and OSM keys/tags to make sure they are linked correctly and translations in my locale are done/accurate. Thanks for reconsidering.
