### ISSUE TITLE
"Distribution of values" diagram has a link to tag with `(other)` value

### ISSUE THREAD

**Issue by skfd** [taginfo/taginfo#272]
I think it should be a link to proper "other" values, or not a link. I know it's a nit-picky issue, but I think I can do it, just need a design direction.

## pro making a less-popular-values screen
Maybe, it would be helpful to link to overpass query that displays only less popular values. It can be dones with regexps by explicitly excluding popular values.

## pro removing link
it's easy to do.

What do you think?

![image](https://user-images.githubusercontent.com/159640/69661169-920bce80-108a-11ea-98af-aa753f1f805e.png)

**Comment by joto** [comment]
It is an oversight that there is a link behind the `(other)`. We should remove that. Linking to Overpass here or something like it would be more surprising/confusing to the user.
