### ISSUE TITLE
JSON download link is over written when switching tabs

### ISSUE THREAD

**Issue by saerdnaer** [taginfo/taginfo#275]
When switching the tabs on  https://taginfo.openstreetmap.org/keys/building#combinations the JSON API link still points to the last loaded tab

## Steps to reproduce
- open https://taginfo.openstreetmap.org/keys/building
- open values tab
- open combinations tab
- open values tab

JSON link points to `https://taginfo.openstreetmap.org/api/4/key/combinations?…` instead of `https://taginfo.openstreetmap.org/api/4/key/values?…`

![taginfo bug](https://user-images.githubusercontent.com/40266/74588905-ea56ca80-5000-11ea-9146-fa2cd6aa03fd.png)

## possible solution

maybe https://github.com/taginfo/taginfo/blob/3b422992c3852e22cd18f609ce96478663b458dd/web/public/js/flexigrid.js#L654 changes the URL of all `pJSON` buttons, and not only the one in the currently opened tab

**Comment by joto** [comment]
Thanks @saerdnaer for the nice report. You found the right spot and it was easy to fix then. Will be on the production server shortly.
