### ISSUE TITLE
Implement "layer_name" in JOSM remote commands

### ISSUE THREAD

**Issue by maxerickson** [taginfo/taginfo#276]
Kind of a minor thing, but nice polish I guess. 

Right now, the "JOSM" button for a page like https://taginfo.openstreetmap.org/tags/addr%3Astate=Aurora ends up giving the layer the name "_meta?" in JOSM. I'm not sure it is documented, but the /import command for the remote accepts further parameters:

https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/io/remotecontrol/handler/ImportHandler.java#L64

One of which is "layer_name" and does what it sounds like, asks JOSM to set a certain name for the layer. I checked that it works okay by hacking the link in the browser inspector:

http://127.0.0.1:8111/import?layer_name=taginfo&url=https%3A%2F%2Foverpass-api.de%2Fapi%2Fxapi_meta%3F*%5Baddr%253Astate%253DAurora%5D

Just setting "taginfo" or so is an improvement but maybe not worth the effort. Setting a name related to the taginfo page would be yet more work but a nice feature.

**Comment by joto** [comment]
I think I have only ever used this when there was an existing data layer in which case it doesn't matter. I'd rather see this as something JOSM should fix, `_meta?` doesn't sound like a reasonable default layer name. Maybe you can ask there.

**Comment by simon04** [comment]
I created a ticket in the JOSM bugtracker: https://josm.openstreetmap.de/ticket/18936#ticket (/import of Overpass xapi_meta URL produces layer with name "_meta?") – JOSM

**Comment by maxerickson** [comment]
Fixed over there now.
