### ISSUE TITLE
Obtain formatter URL for OSM keys from Wikidata and OSM Wikibase

### ISSUE THREAD

**Issue by simon04** [taginfo/taginfo#277]
JOSM uses the "​formatter URL" property from Wikidata and OSM Wikibase in order to turn tags into clickable links.

JOSM documentation: https://josm.openstreetmap.de/wiki/Help/Action/Tag2Link
JOSM ticket: https://josm.openstreetmap.de/ticket/13901

Example P439 "German municipality key – Wikidata":
https://www.wikidata.org/wiki/Property:P439
OSM tag or key (P1282): `Key:de:amtlicher_gemeindeschluessel`
formatter URL (P1630): `http://www.statistik-portal.de/Statistik-Portal/gemeindeverz.asp?G=$1`

Example Q2833 "Freiburg im Breisgau – Wikidata":
https://www.wikidata.org/wiki/Q2833
German municipality key (P439): `08311000` – links to http://www.statistik-portal.de/Statistik-Portal/gemeindeverz.asp?G=08311000

(Followup to our discussion at FOSSGIS 2020.)

**Comment by simon04** [comment]
I've setup a small osmlab project for extracting those formatter URLs: https://github.com/osmlab/tag2link

**Comment by joto** [comment]
I have now implemented my own solution. You can see it in action on [wikidata tags](https://taginfo.openstreetmap.org/tags/wikidata=Q513146), [wikipedia tags](https://taginfo.openstreetmap.org/tags/wikipedia=fr%3AAlg%C3%A9rie%20Poste), [website tags](https://taginfo.openstreetmap.org/tags/?key=website&value=https%3A%2F%2Fwww.burgerking.co.th%2F) and some other tags. See the "Links" section in the "Overview" tab.

The formatter URLs are not nearly enough to make this work reliably. I am checking the value against a regex to immediately rule out anything that has the wrong format. For some tags, more checks are done, for instance the wikipedia tags are checked against a list of all wikipedia sites.
