### ISSUE TITLE
Name= queries are often stuck at "Processing"

### ISSUE THREAD

**Issue by skorasaurus** [taginfo/taginfo#28]
I've noticed over the course of several weeks that some queries take a long time (10+ minutes) to complete, if they complete at all. Most of the queries remain at " 
Page of 1
Processing, please wait..." 

All of these queries that I've experienced this long wait time are for name= or to find what tags are used for certain name= tags (combinations). 

For example: http://taginfo.openstreetmap.org/search?q=name%3DLowe%27s
http://taginfo.openstreetmap.org/search?q=name%3DMeijer
http://taginfo.openstreetmap.org/search?q=name%3DWalgreen%27s
http://taginfo.openstreetmap.us/search?q=name%3DLowe%27s 

I'm having these problems on taginfo.openstreetmap.org and the instance on openstreetmap.us. 

These queries are really useful in scenarios where there are large national or multinational chain stores and restaurants, and the wiki isn't clear of what tag to use. 

Even queries that I'd expect to take long to return like: http://taginfo.openstreetmap.org/tags/highway=residential#combinations
return relatively quick (2-3 seconds) for me.

**Comment by matkoniecz** [comment]
it seems to be fixed nowadays?

Except http://taginfo.openstreetmap.us/search?q=name%3DLowe%27s - but here entire site is down

**Comment by joto** [comment]
All these searches are much quicker these days. Closing here. Please open a new issue if you see problems like this.
