### ISSUE TITLE
Wish: add a button to open iD editor

### ISSUE THREAD

**Issue by Binnette** [taginfo/taginfo#288]
Hi,

Can you please add a button "iD Editor" in the top right corner of taginfo next to the other editors buttons: JOSM and Level0 Editor.

![image](https://user-images.githubusercontent.com/6597721/95011352-6f463100-0630-11eb-8152-8332503e98ed.png)

Thank you & have a nice day.

**Comment by joto** [comment]
The JOSM and Level0 Editor buttons work because you can give the editors the result of an Overpass query for editing. I am not aware of any functionality in the iD editor that would allow something like this. If there is, please point me to the docs.

**Comment by Binnette** [comment]
Hi @joto, ty for your answer. And you are right, iD is not capable to "load" any data.
So iD won't load an overpass query... and will probably never be able to do it...
So i'm clothing this issue. Ty again and have a nice day.
