### ISSUE TITLE
Chronology tab: limit to dates > 2007-10-07

### ISSUE THREAD

**Issue by tyrasd** [taginfo/taginfo#296]
OSM's API version [0.5](https://wiki.openstreetmap.org/wiki/API_changes_between_v0.4_and_v0.5) first exposed the version numbers of OSM objects. See https://www.openstreetmap.org/user/tyr_asd/diary/42449 for a bit of background.

This means that the counts produced from a current history planet file are only accurate back until October 7, 2007. Any values for dates before that are likely not accurate (it's comparable to using a non-history planet file for deducing the object history).

I'd simply limit the x-axis of the graphs to dates > `2007-10-07` to solve this.

**Comment by joto** [comment]
Hm. As the discussion on that diary entry shows the versioning was already there, albeit in the segments maybe. But I thought the history was "faked" when we switched away from segments to show something reasonable? Can you point to an example where the historical data before 2007-10-07 is wrong or misleading?

Not that we'd loose a lot of we limit this to the data from 2007-10-07 onwards...

**Comment by tyrasd** [comment]
```
$ osmium cat germany.osh.pbf --output-format=opl | grep -E " (t2005|t2006|t2007-0)" | cut -d' ' -f2 | sort | uniq -c
2275735 v1
```

is this evidence enough? :wink: 


It's also reflected quite explicitly in Richard's first comment:

> when segments were abolished in the move from 0.4 to 0.5, the history was **not** migrated into the revised database schema.
