### ISSUE TITLE
Chronology tab: use stepped graph instead of linear interpolation

### ISSUE THREAD

**Issue by tyrasd** [taginfo/taginfo#297]
When a tag or key is updated infrequently, the corresponding _chronology_ graph – which currently uses a linear interpolation to fill gaps in the data – may give a false impression of the real development of the counts. Here's an example:

[![image](https://user-images.githubusercontent.com/1927298/99291933-d6b2eb80-2840-11eb-9c80-5c741dd9d1e7.png)](https://taginfo.openstreetmap.org/tags/power=heliostat#chronology)

It would be better to use a stepped line as [in taghistory](https://taghistory.raifer.tech/#***/power/heliostat):

[![taghistory(3)](https://user-images.githubusercontent.com/1927298/99292137-1b3e8700-2841-11eb-83fb-1838bd1ec554.png)](https://taghistory.raifer.tech/#***/power/heliostat)

**Comment by joto** [comment]
You are right, the taghistory graph is more correct. This should be fixed.
