### ISSUE TITLE
Possibly incorrect count of protect_class=97 nodes

### ISSUE THREAD

**Issue by ZeLonewolf** [taginfo/taginfo#299]
The taginfo for the key protect_class=97 reports over 2,000 nodes tagged with that key:
https://taginfo.openstreetmap.org/tags/?key=protect_class&value=97#overview

However, an overpass query indicates that there is only a single node with this tag:
https://overpass-turbo.eu/s/10pg

Other folks on the US slack #overpass channel have been looking at older copies of the planet file and are also finding only a single node, so it does not appear that this is the result of a recent change in the data.

It appears that taginfo is incorrectly reporting >2,000 instances of nodes with protect_class=97 when there is only a single instance.

**Comment by mmd-osm** [comment]
I checked https://planet.openstreetmap.org/pbf/planet-201116.osm.pbf via osmium and only got one node-like entry:

`n1426960800 v3 dV c51780252 t2017-09-06T12:28:01Z i339581 unyuriks TWDPA_ID:ref=147367,name=Golfe%20%de%20%Santa%20%Giulia,natural=bay,protect_class=97,protection_title=Natura%20%2000,ref:IUCN=4,ref:Natura2000=FR9402015,wikidata=Q3110252,wikipedia=fr:Golfe%20%de%20%Santa%20%Giulia x9.2772724 y41.5271348`

**Comment by mmd-osm** [comment]
Ok, I think we can close this one. taginfo results were last updated: "Data from: 2020-11-21 00:58 UTC" as of now.

Respective Overpass query returns 2234 nodes, like taginfo does (https://overpass-turbo.eu/s/10pj )

**Comment by ZeLonewolf** [comment]
Resolved!
