### ISSUE TITLE
Chronology tab: missing x-axis

### ISSUE THREAD

**Issue by pyrog** [taginfo/taginfo#303]
The x-axis seem missing or hidden.

<img width="50%" alt="Chronology tab" src="https://user-images.githubusercontent.com/2158081/99997253-33705200-2dbd-11eb-80cd-4acd7a65476b.png">

**Comment by joto** [comment]
Not only the x-axis, the lower part of the graph is hidden on small screens. This also affects some other pages.

Workaround: Use the browser zoom feature.

**Comment by pyrog** [comment]
> the lower part of the graph is hidden on small screens.

My screen size is 2560 × 1600.

**Comment by dieterdreist** [comment]
on small screens, the graph is cut on the right as well. Zoom is not working.
![Uploading ABE85522-D023-4C57-BC00-D50EA233B5E8.png…]()

**Comment by dieterdreist** [comment]
I managed to get some zoom working by reducing the font size. Changing from portrait to landscape and back then shows the x-axis, but the graph is still cut on the right
![Uploading 84446E10-EFC3-4F66-A66A-A6825C37C94C.png…]()

**Comment by dieterdreist** [comment]
a quick and dirty workaround to make the whole graph accessible can be achieved with this css:
#chart-chronology {
    overflow-x: scroll;
}

**Comment by joto** [comment]
This is now fixed. (Use shift-reload when trying.)
