### ISSUE TITLE
What is the performance of API? How much we should care about it?

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#309]
See https://wiki.openstreetmap.org/wiki/Talk:Wiki#New_Taginfo_Replacement - is switching to this new template on Wiki acceptable? Or is it better to handle in other way?

I ask as I worry about performance impact on taginfo servers and I am unable to judge is it a real problem or not

**Comment by joto** [comment]
I have written something in the wiki thread. Discussion can continue there but I'll leave this issue open as reference for the time being.

**Comment by joto** [comment]
Linkt to the wiki is broken. Closing here as not actionable.

**Comment by tbertels** [comment]
For reference, here's the current link for the discussion above: https://wiki.openstreetmap.org/wiki/Talk:Wiki/Archive_8#New_Taginfo_Replacement
