### ISSUE TITLE
Consider adding new report - popular tags/keys without wiki page with recent growth

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#310]
That would allow to detect low-quality imports, poorly organized paid editing and so on.

See for example https://taginfo.openstreetmap.org/keys/logging%3Astart_date#chronology https://taginfo.openstreetmap.org/keys/garmin_type#chronology https://taginfo.openstreetmap.org/keys/damage%3Aorganization#chronology

It would also allow to detect tags that have ongoing organic use but are not documented

**Comment by matkoniecz** [comment]
Though some blacklist for some values will be needed - there is no need to have wiki pages for `maxspeed` values (I would gladly provide them)

**Comment by joto** [comment]
Not everything needs to be in taginfo itself. I suggest using the API (or the databases build by taginfo) to build these kinds of things.

**Comment by matkoniecz** [comment]
Main benefit of having it in taginfo it would be that it would be used by more than one person (me), but I can also build it on my own as a separate project.

**Comment by matkoniecz** [comment]
Thanks for the great API! It was very easy to write such report, thanks again for writing, documenting and hosting it!

If anyone is curious report produced something like this:

building=plot (increase by 10022 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:building=plot

amenity=waste_dump_site (increase by 6991 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:amenity=waste_dump_site

man_made=tar_kiln (increase by 6924 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:man_made=tar_kiln

man_made=avalanche_protection (increase by 4752 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:man_made=avalanche_protection

highway=removed:street_lamp (increase by 1044 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:highway=removed:street_lamp

natural=tree_group (increase by 716 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:natural=tree_group

natural=ground (increase by 1037 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:natural=ground

natural=hummock (increase by 1715 in last 100 days):
https://wiki.openstreetmap.org/wiki/Tag:natural=hummock

(...)
