### ISSUE TITLE
"wizard_area": "in France métropolitaine" produce not-working overpass turbo link

### ISSUE THREAD

**Issue by Marc-marc-marc** [taginfo/taginfo#318]
setting "wizard_area": "in France métropolitaine" produce overpass turbo link like https://overpass-turbo.eu/?w=%22oneway%22%3D%22estate_agent%22+in+France+m%C3tropolitaine
thislink doesn't work. no idea if it's a error in the setting or the wizard_area isn't escaped properly or an overpass turbo bug

**Comment by joto** [comment]
This is something the owner of the site has to fix in their config file: 

```
    "wizard_area": "in \"France métropolitaine\""
```

**Comment by Marc-marc-marc** [comment]
thanks
