### ISSUE TITLE
Chronology broken for some tags - maybe chronology is confused by mass added tags

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#319]
See https://taginfo.openstreetmap.org/tags/service=NS%20Coordinate%20Control%20Station#chronology

![screen15](https://user-images.githubusercontent.com/899988/112747085-65840180-8fb3-11eb-95f1-29bdbc71a6c0.png)
![screen14](https://user-images.githubusercontent.com/899988/112747086-67e65b80-8fb3-11eb-9480-ca033d5d8fd2.png)

Is chronology confused by presence of only a single day when tag count changed? (BTW, is there chance to have API replying by not omitting days where tag count was not changed - is it intentional to skip such days? For normal tags it has no effect but for mass imported ones it requires adding extra date handling)

I initially thought that bug is triggered by spaces, but https://taginfo.openstreetmap.org/tags/name=Main%20Street#chronology works fine

BTW, it seems to be an undiscussed import so it is likely that tags will be removed soon ( https://www.openstreetmap.org/changeset/101215111 )

**Comment by joto** [comment]
There is a single dot in the middle at the top of the image, because that's the only time something changed. Not ideal. We would probably expect a step from zero to that value and then a horizontal line. I'll have to look into that.

Re API: Yes this was intentional to keep the amount of data down.

**Comment by matkoniecz** [comment]
> There is a single dot in the middle at the top of the image

oh, I missed it. I was looking toward right

> We would probably expect a step from zero to that value and then a horizontal line.

Yes, exactly

> Re API: Yes this was intentional to keep the amount of data down.

oh well, I guess that I was not fighting with dates in my code durinbg this year so far and time for that has come

BTW, thanks again for this amazing tool - it is extremely useful!

**Comment by joto** [comment]
This is fixed now.
