### ISSUE TITLE
Suggestion : animated gif over the map page

### ISSUE THREAD

**Issue by overflorian** [taginfo/taginfo#321]
Hi,
I suggest that the "map" tab shows an animated gif displaying the evolution of the data.
Instead of having an _averagely useful map_ such as this one:
![image](https://user-images.githubusercontent.com/11553211/114748115-dec07a00-9d51-11eb-88cd-83b1ed0fc2c4.png)
We could instead visually see the evolution of the tag in the world over time.

Also I think that such an animated gif would be a perfect tool for a better promotion over the social medias.

**Comment by joto** [comment]
While I agree that it would be cool to have something like this, the amount of data this would need is probably beyond what we can do within taginfo. It would need a lot more processing time to generate something like this generally for all tags. And generating the low-res images we have is already by far the biggest drain on memory. Adding the history dimension would compromise taginfos ability to run on small servers and in a reasonable about of time for not that much gain. There are other tools that can generate these kinds of movies, so I think we better leave this for the specialized tools.

**Comment by overflorian** [comment]
Thanks for your reply @joto. It absolutely makes sense to me.
Anyway, I have to ask, just in case: if I manage to find you some server resources for that, would you be interested in developing it? I can ask gently to OpenStreetMap France if so ;)

**Comment by joto** [comment]
@overflorian Thanks for the offer, but this isn't about one instance, this is a general issue to keep taginfo lean and mean.

**Comment by overflorian** [comment]
Sure, I got it. Regards
