### ISSUE TITLE
Why haven't got a Simplified Chinese translation version

### ISSUE THREAD

**Issue by LaoshuBaby** [taginfo/taginfo#322]
Accroding to the [translations overview](https://taginfo.openstreetmap.org/taginfo/translations), taginfo now have a Traditional Chinese version translation, but haven't got a Simplified.
In mainland of China most people use Simplified character for daily work and reading, and some verbs/nouns are translated to different words between those two different Chinese.

![图片](https://user-images.githubusercontent.com/42690037/115103556-47dc0380-9f85-11eb-9ed4-5bb982b6f060.png)

So will taginfo have some idea about this?

**Comment by LaoshuBaby** [comment]
we need ```zh_CN``` !

**Comment by joto** [comment]
Feel free to contribute a translation. Here is how to do it: https://wiki.openstreetmap.org/wiki/Taginfo/I18N
