### ISSUE TITLE
No combinations for layer=1

### ISSUE THREAD

**Issue by zstadler** [taginfo/taginfo#332]
The [combination tab for "layer=1"](https://taginfo.openstreetmap.org/tags/?key=layer&value=1#combinations) is empty.

Given that ["1" is the most frequent value of "layer"](https://taginfo.openstreetmap.org/keys/layer#values) and that ["highway" is the most frequent combination with "layer"](https://taginfo.openstreetmap.org/keys/layer#combinations), I would expect to see some `highway` tags combined with `layer=1`

The combination tab is also empty for other popular "layer" values, such as ["-1"](https://taginfo.openstreetmap.org/tags/layer=-1#combinations) and ["2"](https://taginfo.openstreetmap.org/tags/layer=2#combinations).

**Comment by joto** [comment]
This is fixed now. For some reason lost to history the combinations for the `layer` tag and some others were not calculated, probably because I thought at that time that this would add too many combinations to calculate. Today there are so many tags it doesn't matter.
