### ISSUE TITLE
Couldn't see full page in high zoom level, even Firefox's default 100%

### ISSUE THREAD

**Issue by LaoshuBaby** [taginfo/taginfo#334]
**This is the Translations Overview page:**

This problem occur in there
https://taginfo.openstreetmap.org/taginfo/translations

**Here is the display in 100%:**

You can see it show me 20 language
![图片](https://user-images.githubusercontent.com/42690037/135831096-4f98d15d-a723-472e-8048-1e98bb4e65b6.png)

**Then I set my zoom to 80%**

Full list of 23 language
![图片](https://user-images.githubusercontent.com/42690037/135831301-6247d7b7-8f54-4507-9b76-82afb9b01bd3.png)

**If using 130%**

Oops! only 16 language left
![图片](https://user-images.githubusercontent.com/42690037/135831433-865d5b2e-1b8c-410c-a062-c5b00b437042.png)

-----

**My environment:**

OS: Microsoft Windows 10 Professional 10.0.19043 Build 19043
Browser: Firefox 92.0.1
Browser locale:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Display：
![图片](https://user-images.githubusercontent.com/42690037/135830905-51d5ab6e-3901-4942-b28f-fa9b8278674d.png)
High resolution zoom:
![图片](https://user-images.githubusercontent.com/42690037/135830977-df0e7e64-a680-4016-a81f-22a67f331c01.png)

-----

**Last**

Yes, this is not a major bug in taginfo because seldom user will see this page, only translator will look.

But this is truly a bad experience thing.

Therefore, whether it is repaired or not is actually not a big impact. I just found and wrote it in this issue.

**Comment by joto** [comment]
Thanks for the report. The fix will show up on the site soon.
