### ISSUE TITLE
Arabic lang RTL display

### ISSUE THREAD

**Issue by abdullahO2** [taginfo/taginfo#337]
hello
Please make the Arabic language display from right to left in the same way that the Persian language appears:
https://github.com/taginfo/taginfo/issues/236
regards
abdullah

**Comment by abdullahO2** [comment]
done by @hubaishan https://github.com/r18n/r18n-core/pull/32

**Comment by joto** [comment]
Thanks. The taginfo display should now work correctly.

**Comment by abdullahO2** [comment]
Yes, the texts appeared correctly on the site, thank you very much and kind regards
