### ISSUE TITLE
Cannot visually differenciate between Latin & Cyrillic characters

### ISSUE THREAD

**Issue by amandasaurus** [taginfo/taginfo#343]
Currently there are [970 `addr:city=Русе`](https://taginfo.openstreetmap.org/tags/addr:city=%D0%A0%D1%83%D1%81%D0%B5), and [125 `addr:city=Pyce`](https://taginfo.openstreetmap.org/tags/addr:city=Pyce). The first is in Cyrillilc, the second is a mistake using latin characters that look like the cyrillic.

Currently, a user cannot tell apart which is which because they all look the same in taginfo. I think this is a lacking feature, but I'm unsure what the solution is.

* Use a different font which will display latin & cyrillic letters differently?
* Display some unicode details of a tag/value?
* Use HTML `<span title=…`/`<acronym>` tags on all the letters in a key/value (seems a bit heavy)

```
$ uniwhat "Русе"
character   byte  UTF-32  encoded as     glyph    name
        0      0  000420  D0 A0            Р      CYRILLIC CAPITAL LETTER ER
        1      2  000443  D1 83            у      CYRILLIC SMALL LETTER U
        2      4  000441  D1 81            с      CYRILLIC SMALL LETTER ES
        3      6  000435  D0 B5            е      CYRILLIC SMALL LETTER IE
```
and 
```
$ uniwhat "Pyce"
character   byte  UTF-32  encoded as     glyph    name
        0      0  000050  50               P      LATIN CAPITAL LETTER P
        1      1  000079  79               y      LATIN SMALL LETTER Y
        2      2  000063  63               c      LATIN SMALL LETTER C
        3      3  000065  65               e      LATIN SMALL LETTER E
```

**Comment by Dimitar5555** [comment]
As a person who speaks Bulgarian (which uses Cyrillic letters) I can offer some insight.

> One problem is, that I can't know what the "correct" characters should be in the general case, if there is a "correct" at all.

That's true, but it would be nice to know when Cyrillic and Latin letters are mixed in the same key value. Usually that's something that should be avoided (there may be edge cases but it's definitely an error when it happens on `addr:streetname`, `addr:city` and other `addr:*`). Another edge case could be Serbian since the Serbian language uses both Cyrillic and Latin letters.

> What would actually be useful to show (as compared to just interesting)?

It would be useful to show the glyph and character name like uniwhat shows them. 

> What problem are we trying to solve?

Mixing Latin and Cyrillic letters in the same key (mostly `name:*`, `name` and `addr:*`.

**Comment by Zverik** [comment]
Using different font or colours for entire values would be not only not useful, but also harmful, for reading mixed-language values would become harder and slower (think numbers).

What could be useful is flagging values with _words_ that contain letters from different alphabets. For example, `c` and `с` (latin "c" and cyrillic "s") look the same and reside on the same keyboard key, so it's a common error to mix up these two. And that definitely impedes searching, for example.

**Comment by amandasaurus** [comment]
On Fri, 03 Dec 2021 14:07 +01:00, Jochen Topf ***@***.***> wrote:
> What problem are we trying to solve? Then we can think about *how* to do that.

Someone in Bulgaria noticed the 2 different `addr:city` values. They wanted to fix the OSM data. If they pressed the “Overpass Turbo”/“JOSM” link they could open it and fix it. But they didn't know which one was right, and which was wrong. I copy & pasted from taginfo website and ran it through `uniwhat` to figure out which was right. That's a problem. I'm not sure how to solve it...

**Comment by amandasaurus** [comment]
On Fri, 03 Dec 2021 14:07 +01:00, Jochen Topf ***@***.***> wrote:
> My plan was to "somehow" do something like what your 
> `uniwhat` examples shows. But I never could figure out what to do 
> exactly and how to show it.

What about another tab, which shows the detailed break down of the unicode characters in the key, and value, which shows similar output to `uniwhat`? Then you are not deciding “Latin alphabet is right”, you are merely providing a deep dive into the “binary” representation of the tag.

In the case of homoglyphs, a mapper can deduce which is latin & which is cyrllic.

**Comment by joto** [comment]
This was one of those "how hard can it be?" things I thought I can quickly do... Took me two days of fiddling around with strange tables of unicode scripts, properties, etc. But now there is a new "Characters" tab on key/tag/relation pages which show a table of all characters used along with the script and unicode general category and unicode name of that code point.

**Comment by amandasaurus** [comment]
> The Programmers’ Credo: we do these things not because they are easy, but because we thought they were going to be easy

https://twitter.com/Pinboard/status/761656824202276864

Thanks, I think this solves the root cause of this issue. 🙂
