### ISSUE TITLE
API : Chronology deltas don't reflect current tag count

### ISSUE THREAD

**Issue by PanierAvide** [taginfo/taginfo#350]
Hello,

I'm trying to do some statistics using chronology API from Taginfo, but it seems that there's an issue in returned values. Let's take an example :

- amenity=hotel is currently used 0 times in OSM data according to https://taginfo.openstreetmap.org/tags/amenity=hotel
- Summing all delta day by day of API result ( https://taginfo.openstreetmap.org/api/4/key/chronology?key=amenity&value=hotel ) doesn't give a final value at 0, but instead ~20 million (node/way/rel mixed). Even if I messed up script on my side, just looking at recent values in API response seem quite odd (19 and 20 january 2022 each having +5000 tags).

Other example, embassy=embassy ( https://taginfo.openstreetmap.org/tags/embassy=embassy#chronology ) had a like 600 count drop near January 2022, and summing all negatives values returned by https://taginfo.openstreetmap.org/api/4/key/chronology?key=embassy&value=embassy gives you an overall 160 count drop.

Maybe issue is related to how tag removals are counted, and some data is missing to have accurate result ?

Best regards.

**Comment by joto** [comment]
You are accessing the wrong API endpoint. `https://taginfo.openstreetmap.org/api/4/key/chronology?key=amenity&value=hotel` will ignore the `value` parameter and return the results for the `amenity` **key** only. You have to use `https://taginfo.openstreetmap.org/api/4/tag/chronology?key=amenity&value=hotel` (**tag** instead of **key**) for tags. But that doesn't return anything, because chronology is only kept for the most common tags.

**Comment by PanierAvide** [comment]
Thanks for your fast feedback, that's right it works better when using correct API route :sweat_smile: 

Could it be interesting to have an alert when using key+value params on `/api/4/key/chronology` to be more consumer friendly ?

**Comment by joto** [comment]
We don't have a way of issuing a warning on an API call, so they only thing we could to is fail with an error message. I am not sure this would be the right thing to do. I have to think about that. I opened issue #351 for that.
