### ISSUE TITLE
Projects tab shows wildcard matches before specific matches

### ISSUE THREAD

**Issue by 1ec5** [taginfo/taginfo#356]
The Projects tab for a tag value sorts wildcard entries first, so you see all the manners in which projects support the key generically before finding out how some projects give special treatment to the specific tag value.

For example, the [`building=apartments`](https://taginfo.openstreetmap.org/tags/building=apartments#projects) project listing relegates `building=apartments` consumers to the second page in my browser window (which can fit 15 rows at a time). Since this is the `building=apartments` page, it would be more interesting to know that StreetComplete includes `building=apartments` in its Building Levels quest than that OSM Buildings skips `building=no`.

OpenStreetMap Americana is certainly the only data consumer that specifically supports the [`network=US:US:Alternate:Truck:Business`](https://taginfo.openstreetmap.org/tags/network=US%3AUS%3AAlternate%3ATruck%3ABusiness) tag value that’s specific to one town in Pennsylvania, but once taginfo/taginfo-projects#127 lands, it’ll be buried behind pages of wildcard matches from JOSM user presets about European traffic signs and Philippine jeepney services.

Does the Projects tab on a tag value page need to show wildcard matches, which are already listed under the key’s page? If so, perhaps the table should be sorted so that specific matches come before the wildcard matches. Since there can only be two possible values in this column, defaulting to descending sort order on the Tag column would address this issue, though it would be nice to preserve ascending sort order on the Project column.

**Comment by joto** [comment]
Your proposed change sounds very reasonable, so I have changed it. Thanks for the report. Can take an hour or so before it appears on the site.
