### ISSUE TITLE
/api/4/projects/tags fails on example call

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#367]
I tried to get https://taginfo.openstreetmap.org/taginfo/apidoc#api_4_projects_tags to work but I am confused

Example from https://github.com/taginfo/taginfo/blob/34676f568d61c1a3a6b8fd965107e04a6b645524/web/lib/api/v4/projects.rb#L126 gives https://taginfo.openstreetmap.org/api/4/projects/tags?page=1&rp=10&sortname=key&sortorder=asc that gives

> Internal Server Error

https://taginfo.openstreetmap.org/api/4/projects/tags does the same, just after longer time

note: I have not made thorough investigation here

**Comment by joto** [comment]
The docs are wrong. The sortname should be 'tag', not 'key'.
