### ISSUE TITLE
Uncaught SyntaxError: private fields are not currently supported taginfo.js:702:4

### ISSUE THREAD

**Issue by peternewman** [taginfo/taginfo#371]
I've just started getting this error on the main taginfo site (admittedly on my slightly ageing Firefox install). The GB and US ones are okay, so I assume they're a bit behind:
Uncaught SyntaxError: private fields are not currently supported taginfo.js:702:4
https://github.com/taginfo/taginfo/blob/b1d291fa674da4111cd570144f122d0175dd4ed7/web/public/js/taginfo.js#L702

Which appears to have been introduced in:
https://github.com/taginfo/taginfo/commit/d4d8f2d7360e0220fcacff21040d532b792b7cd3

This suggests maybe it's just some missing quotes, but I'm guessing it's perhaps not quite that simple as it's a more jquery usage:
https://stackoverflow.com/a/69038095

Or two other more relevant looking workarounds:
https://github.com/mrdoob/three.js/pull/22438
https://github.com/mrdoob/three.js/pull/22441

**Comment by joto** [comment]
Should be fixed, but it can take an hour or so until it shows up on the taginfo site. You might need a shift reload.

Still: I'd recommend installing a newer browser version.

**Comment by peternewman** [comment]
> Should be fixed, but it can take an hour or so until it shows up on the taginfo site. You might need a shift reload.

Yes that's done the trick thanks.

> Still: I'd recommend installing a newer browser version.

Yeah noted, should happen eventually for various reasons...
