### ISSUE TITLE
Chronology and map graphs are not 100% visible on mobile screens

### ISSUE THREAD

**Issue by Dimitar5555** [taginfo/taginfo#373]
Currently if you slide left on a mobile device, part of the graphs are missing which makes them useless. 

![image](https://user-images.githubusercontent.com/19364673/185960316-985155ff-720e-48eb-a7fb-cbf8573b236e.png)

In order to fix this issue, you have to remove the `display` property from the `div`s with ids `chronology` and `map`. Then you have to add this code in `taginfo.css`:

```
@media only screen and (hover: hover) and (pointer: fine){
    #chronology, #map {
        display: block;
    }
}
```

The media queries are used in order to detect mobile devices.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover

**Comment by LuisAPI** [comment]
Can confirm problem still persists.

![Screenshot_20230228-095656_Samsung Internet](https://user-images.githubusercontent.com/7901433/221733330-49afa99f-96b4-4b6c-b442-860bbfbd5bf2.jpg)

**Comment by Dimitar5555** [comment]
The issue has been fixed recently.
![image](https://user-images.githubusercontent.com/19364673/229276626-9a901565-f290-49f4-86d4-f6cd88323ab3.png)
