### ISSUE TITLE
Unlock #366

### ISSUE THREAD

**Issue by angoca** [taginfo/taginfo#375]
Can you unlock the issue #366 to continue talking about the Taglist feature request? 

In fact, the status from the wiki is currently organized based on just one spelling for each status. We have already organized the status.

**Comment by joto** [comment]
Still a mess:

```
sqlite> select approval_status, count(*) from wikipages group by approval_status;
|11312
Abandoned|26
Approved|3882
De Facto|7
De facto|983
Deprecated|67
Discardable|1
Draft|139
Imported|1
In Use|162
In use|6027
In use
-->|1
Obsolete|7
Proposed|226
Rejected|3
Undefined|1
abandoned|35
approved|815
de facto|3419
deprecated|197
discardable|33
draft|114
imported|174
in Use|5
in use|2300
inuse|2
obsolete|34
proposed|263
rejected|5
```

But I'll unlock that issue.

**Comment by angoca** [comment]
Just for my understanding, how this sqlite database is generated?

**Comment by joto** [comment]
With the scripts here: https://github.com/taginfo/taginfo/tree/master/sources/wiki

You can download the sqlite database here: https://taginfo.openstreetmap.org/download
