### ISSUE TITLE
wish: translation of the keys ,tags and descriptions in other languages

### ISSUE THREAD

**Issue by yopaseopor** [taginfo/taginfo#379]
Managing a translation of the wiki in a language is so difficult. Our time is limited. To be or not to be. Translate or map. But a good emergency solution could be the translation of the keys ,tags and descriptions. People could search and find a lot of values that they don't know there is a existing way to map some of them in their language. Why not?

**Comment by joto** [comment]
I don't understand what it is that you want or why this has anything to do with taginfo.

**Comment by yopaseopor** [comment]
When you are fluent in English is easy to understand how to use the keys and guess an specific tag, key and value. But when you are not fluent in English you can only access to the translation of the wiki and to the main tags. What value is for a "Estibador"? What tag do you use to define "Consigna de paquetes" ? 
Taginfo is the service where you can consult ALL the keys, values and tags of OSM. The translation of the interface is useless if we don't know what we want to search.
Collaborative translation of the keys, values and tags of Taginfo could be a powerful international tool to mapper who aren't fluent in English. And the efforts of translating keys and values is less than translation all the page of a wiki.
OSM wiki in English > 4510
OSM wiki in German > 837 (20% of English)
OSM wiki in Portuguese (Brazilian also) > 427 (10% of English)

**Comment by joto** [comment]
Tag descriptions are in the wiki and translated there and taginfo will pick up those translations automatically. Nothing extra to do. If you don't see translated descriptions of tags for some tags that's either because nobody did the translation yet or because there are buried in the wikidata mess in the wiki.
