### ISSUE TITLE
Description is missing

### ISSUE THREAD

**Issue by geozeisig** [taginfo/taginfo#380]
The description is missing on the Values card. It may be a bug that is new. That was correct a few days ago.

**Comment by joto** [comment]
I don't understand what you are referring to? Can you give us a URL and describe exactly what's wrong?

**Comment by geozeisig** [comment]
![Taginfo](https://user-images.githubusercontent.com/17127509/198339485-2e37d6b5-bff9-4f6b-9cbc-54437c67d24c.jpg)

**Comment by joto** [comment]
Ups. Looks like I introduced a bug there. Hopefully fixed tomorrow.

**Comment by joto** [comment]
Fixed.
