### ISSUE TITLE
Spanish regions databases

### ISSUE THREAD

**Issue by Crashillo** [taginfo/taginfo#381]
I noticed that all spanish region databases return error (**500: Internal server error**). That is:

- https://taginfo.geofabrik.de/europe/spain/andalucia
- https://taginfo.geofabrik.de/europe/spain/aragon
- https://taginfo.geofabrik.de/europe/spain/asturias
- ...

Is there any way to fix this issue? OSM Spanish community would appreciate that so much.

**Comment by joto** [comment]
Nothing to do with the taginfo software. Next time report this to Geofabrik, they are running these services. I have notified them.

**Comment by Crashillo** [comment]
Yep, I did so 2 weeks ago, I wrote them to <info@geofabrik.de>. If you get luckier than me, please share their feedback here.
