### ISSUE TITLE
Compare: Allow shuffling/sorting of items

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#386]
The user should be able to move items around, or sort them by certain properties (alphabetically on name, occurences, nr. of projects) where possible. It may also be possible to implement hotkeys for these actions.

Ex. moving one item in front of another (could be done by dragging with/without a button, or a generic sorting button)
![image](https://user-images.githubusercontent.com/67521919/210178857-600ee76a-ee2b-4212-9976-4c5a53e65d1c.png)

**Comment by joto** [comment]
Adding interactivity here would need a lot of code. I am not using any framework where you can just make things drag-and-droppable without any effort. And the need for that is a bit questionable. Sure, it would be nice, but how important is that? Why do you think this is needed?

Note that you can always edit the URL if you really want to show items in a certain order.

**Comment by danieldegroot2** [comment]
It would allow the user to show e.g.
- the default tag / the one which is most important to them (always) in first position for example; or
- display i.e. 3 tags in ascending order of uses to show a relationship between them. Though, this is also achieved with #384.

Editing the URL is always a welcome option, but should not be needed for the casual user.

**Comment by joto** [comment]
As I said, not important enough to warrent the extra code and effort.

**Comment by danieldegroot2** [comment]
That's ok.
