### ISSUE TITLE
Projects: Allow searching in usage description

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#387]
Wishlist item; it may only apply to a few projects, and few cases - and searching keys/tags is more efficient in that case.

to find keys/tags you may otherwise miss, or which may be relevant/related, you could search for similar/related wording inside usage descriptions, and across projects.
Of course, this can already be done in some way
- for a single project in their json file with Ctrl+F, so for something like [SomeoneElse: Rural pedestrian CartoCSS maps](https://taginfo.openstreetmap.org/projects/someoneelse_style#overview), which renders numerous keys/tags as the same object type in a single map style / theme, it may not be so useful
- yet, it could help in getting an overview when projects have longer descriptions and have related usage spread across their file(s), though for this you could also create a filter in Excel).

**Comment by joto** [comment]
This goes way beyond what taginfo can do in some automated fashion. For one, descriptions from projects are sometimes quite good, sometimes non-existent. But we can't add interfaces for everything. Use the API if you want to do something special or download the database and do some SQL querying.

**Comment by danieldegroot2** [comment]
Thanks for the reply. Sorry again for any non-actionable ideas.
