### ISSUE TITLE
Projects: Allow filtering by object type

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#388]
Allow users to filter what keys/tags a project uses for a given object type.

Ex. "Filter to only nodes" would show all keys/tags which are used and are only used if they are mapped as a node.

(two of those entries which would be displayed highlighted inside an example search and project)
![image](https://user-images.githubusercontent.com/67521919/210180652-6da85cc1-0d71-46b4-b37f-ca9afaf16e34.png)

(Filtering multiple object types may be more complicated and it is understandable this isn't going to be a feature anytime soon.)

**Comment by joto** [comment]
Can you say something about your use case? Why this specific filter? Why not filter items by the number of uses etc.?

Sure it would be nice to have all sorts of filtering, but then that has not only to be implemented but also the user has to understand what they can do and be able to do it.

**Comment by danieldegroot2** [comment]
Sorry, it's probably not so useful, actually. It could help find things to map for a project when out using i.e. Every Door (at least ones you wouldn't have to change into another object type afterwards).
(it could also maybe help find if a project is lacking support for an object type for some tags, but this is not so important.)

Closing as it's not actionable.
