### ISSUE TITLE
Projects: Compare projects

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#391]
Allow to compare key/tag usage across projects.

Different projects may use different tags, icons and descriptions to describe the same thing, or may use additional tags to show additional information which other projects don't. (i.e. they consider different tags for routing, or different descriptions for different target audiences).

(There may be additional comparisons possible)

**Comment by joto** [comment]
Can you elaborate what you want to see here?

**Comment by danieldegroot2** [comment]
I've edited the top post.

> Can you elaborate what you want to see here?

Show keys/tags for two or more projects alongside each other.

Allow the user to for example
1. Go to the Projects page.
2. Search a theme they like (or otherwise find relevant projects to compare).
3. Select two or more projects from the list
4. Click a "Compare" button.
5. A list is shown of tags either project uses
6. Next to them are two or more columns with checkmarks to show which project uses said tag.
7. The list could be filtered to only show tags which are used by one project, or only by a specific project.
8. This list could then be searched to refine further which tags are compared.

Optionally, the user could compare iconography or descriptions.

This may lose usefulness just due to the shear quantity of tags (especially subkeys) being used by some projects which are not in use by other (smaller) projects.

**Comment by joto** [comment]
This sounds all very ambitious, but the actual lists of keys and tags for the projects just don't allow anything remotely that useful. We'd need a lot more metadata in those lists to compare them in some automated way like this. You really have to read the description and probably click through to that project and look at the details to see what the project is actually doing with that tag.

This is certainly something I'd want to have but it is quite a "pie in the sky" issue so I am closing that here.

**Comment by danieldegroot2** [comment]
Thanks. I understand.
