### ISSUE TITLE
wiki_pages_about_non_existing_keys report is not very useful

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#399]
https://taginfo.openstreetmap.org/reports/wiki_pages_about_non_existing_keys

For start, some pages may document now deprecated tag that are fully eradicated. That is fine and there is no reason to delete it

And many of them are redirects - maybe not highly useful but still not worth deleting (there are far better targets for cleanup like say `barrier=gate2` tags and so on).

**Comment by joto** [comment]
The usefulness of that report might be limited, but it is there. I am not removing working code.

**Comment by matkoniecz** [comment]
Is there any plausible use how this page may help or used in way to be helpful? Is it deliberate that it is suggesting that harmless redirects should be deleted?

**Comment by joto** [comment]
I don't know where you get the idea from that it is "suggesting that harmless redirects should be deleted".

**Comment by matkoniecz** [comment]
It seemed to me that this page falls under 'Some of the reports can help with finding specific errors." and indicates broken/not needed wiki pages. If it not intending to do that I am unsure what is its purpose and I badly guessed its purpose.
