### ISSUE TITLE
Searching for keys fails due to "412 Precondition failed"

### ISSUE THREAD

**Issue by mnalis** [taginfo/taginfo#401]
When using a search box on the top right of https://taginfo.openstreetmap.org/ it leads to (for example):

https://taginfo.openstreetmap.org/search?q=camping#keys

that however just spins and no results are returned. I've tried many times in several hours today. It worked few days back just fine. (Manually opening URL for that key https://taginfo.openstreetmap.org/keys/camping#values works just fine).

Looking at network details, it seems to try to fetch e.g.:
https://taginfo.openstreetmap.org/api/4/keys/all?query=camping&sortname=count_all&sortorder=desc&page=1&rp=-4
which keeps failing with `412 Precondition failed` and error text `"results per page must be integer between 0 and 999"`

Indeed, manually chaging that `rp=-4` seems to produce results fine:
https://taginfo.openstreetmap.org/api/4/keys/all?query=camping&sortname=count_all&sortorder=desc&page=1&rp=10

I have no idea why the search on main page https://taginfo.openstreetmap.org puts that `rp=-4` there. I've tried force-reloading, and trying in other browsers with cleared cache and no adblocker, and it still fails the same, so it is probably not related to https://github.com/taginfo/taginfo/issues/397 (only other issue I've found recently with related problem)

**Comment by joto** [comment]
I have done some extensive refactoring on the taginfo site in the last days and broken some things while doing that. This should all work now again. Please try a shift reload now.

**Comment by arch0345** [comment]
Searching for keys now works, however searching for tags is still broken. For example, searching for `building=yes` infinitely loads and doesn't return any results:
https://taginfo.openstreetmap.org/search?q=building%3Dyes#tags

It looks like this is a similar issue in which the results per page is set to -4.

**Comment by joto** [comment]
Thanks @arch0345, this should work now. (Use shift-reload when trying.)

Closing this here. Please open a new issue if you find any other problems.
