### ISSUE TITLE
Adjust text overflow

### ISSUE THREAD

**Issue by danieldegroot2** [taginfo/taginfo#402]
On the main page, links at the end of the info boxes which take up multiple lines overflow out of the box onto the white background.

It would be neat if info box text was kept inside the grey boxes, also when the last bit takes multiple lines, or when zooming.

Happens on regular displays too, ignore screenshot if it looks off.
![image](https://user-images.githubusercontent.com/67521919/229280908-427d9514-6d7b-4375-a7b0-0a05d832799a.png)

Browser(s): Chrome, Firefox (probably all common browsers)

**Comment by joto** [comment]
This should be fixed now.

**Comment by danieldegroot2** [comment]
Seems to. Btw, the word "support" at the bottom of the word cloud is cut off in my session.

![image](https://user-images.githubusercontent.com/67521919/229348394-fd360b82-0ba7-46a0-b8d0-b06ff82ecfae.png)
