### ISSUE TITLE
Filter relations by subtype

### ISSUE THREAD

**Issue by pyrog** [taginfo/taginfo#406]
The analysis could be deeper with a filter by subtype i.e. `route=hiking` for relation `type=route`.
This filter could be added to **Overview**, **Roles**, **Roles Graph** and **Project** tabs?

<img width="100%" alt="Overview" src="https://user-images.githubusercontent.com/2158081/232231239-6f7c4320-0f43-4cf4-873f-40b7ea34e424.png">
<img width="100%" alt="Roles" src="https://user-images.githubusercontent.com/2158081/232231246-8cfaa413-6f24-4579-aeab-6c5145d2d6c3.png">
<img width="100%" alt="Roles Graph" src="https://user-images.githubusercontent.com/2158081/232231262-2bfd2ef4-d337-4f2a-b6a5-3a3592b41512.png">
<img width="100%" alt="Project" src="https://user-images.githubusercontent.com/2158081/232231404-cae1592b-8090-402f-90d1-816d8d216913.png">

**Comment by joto** [comment]
Yes. But at some point we have to draw the line of what a generic tool like taginfo can do. The architecture of taginfo doesn't allow us to do finer and finer dinstinctions here, it would be quite some effort to do something like this. Maybe this is something some other tool can do.
