### ISSUE TITLE
Question: Update OsmAnd link for taginfo

### ISSUE THREAD

**Issue by vshcherb** [taginfo/taginfo#411]
Hello, sorry probably creating issue in the wrong place. 

We (OsmAnd) were updating building system and we have new URL for taginfo system - https://creator.osmand.net/taginfo.json.

If you know the right place to contact please let me know

**Comment by joto** [comment]
Please create a PR as described in https://github.com/taginfo/taginfo-projects/blob/master/CONTRIBUTING.md and 
https://wiki.openstreetmap.org/wiki/Taginfo/Projects .

**Comment by vshcherb** [comment]
Thanks!
