### ISSUE TITLE
Browser history inconsistency

### ISSUE THREAD

**Issue by mueschel** [taginfo/taginfo#433]
When navigating through the key pages, the browser history is behaving strangely.

As an example: You're on the search results page, click on a key, then on the tab "chronology".

Expected:  go back and forth by two steps to change between results, overview and chronology.

**Firefox 124**
- back: URL changes to "#overview", page doesn't change
- back: URL changes to no "#", page doesn't change
- back: URL and page change to search result
- forward: URL and page change to "#overview"
- [end of history!]

Browsing history backwards, there's no way to get to the Overview, and one more step than expected
Browsing history forwards, there's no way to get to the Chronology page

**Chrome 122 / Chromium 122**
- back: URL changes to "#overview", page doesn't change
- back: URL and page change to search result
- forward: URL changes to "#overview", page changes to Chronology
- forward: URL changes to "chronology", page doesn't change

Browsing history has the correct number of steps, but the page doesn't change according to the URL displayed.

**Comment by joto** [comment]
I can reproduce the problem. This is most likely due to taginfo changing the URL without using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).
