### ISSUE TITLE
Specific tag not in Combinations list

### ISSUE THREAD

**Issue by martinstingl** [taginfo/taginfo#434]
https://taginfo.openstreetmap.org/tags/?key=amenity&value=hunting_stand#combinations
Worldwide should be more than 5000 nodes tagged with amenity=hunting_stand and raised=*, but raised=* (or raised=yes/no) is not shown in the list. 
The last entry currently has a count of only 1221 so I am wondering why this is not included.

**Comment by joto** [comment]
A tag needs at least a count of 10.000 to be even considered for counting in combinations. `raised` only has about 5.000.
