### ISSUE TITLE
(Regional Taginfo): JSON Link does not contain regional URL part

### ISSUE THREAD

**Issue by tordans** [taginfo/taginfo#438]
This issue is only on the [regional taginfo instances](https://taginfo.geofabrik.de/). Is there a better repo / place to report this or can we maybe ping the person maintaining it here?

---

Issue:
The JSON link on the values page links to a target that does not contain the `europe:germany` part of the URL that I open it from which results in wrong data being presented.

Steps:
1. https://taginfo.geofabrik.de/europe:germany/keys/traffic_sign#values 
2. Open JSON URL
   - Wrong: https://taginfo.geofabrik.de/api/4/key/values?key=traffic_sign&filter=all&lang=de&sortname=count&sortorder=desc&rp=17&page=1
      This shows data like …, which is not what we see on the page
      ```
            "value": "city_limit",
            "count": 7,
      ```
   - Right: https://taginfo.geofabrik.de/europe:germany/api/4/key/values?key=traffic_sign&filter=all&lang=de&sortname=count&sortorder=desc&rp=17&page=1
      Shows the right data
      ```
      "value": "city_limit",
      "count": 112565,
      ```

----

Btw, thank for the regional instances, they are super handy!

**Comment by joto** [comment]
@woodpeck Your issue.
