### ISSUE TITLE
Distributions for tag combinations

### ISSUE THREAD

**Issue by tordans** [taginfo/taginfo#440]
I am looking for easy ways to review the usage of tag combinations by country. Eg for https://github.com/openstreetmap/id-tagging-schema/pull/1327#issuecomment-2452855557

Taginfo has the distribution maps for one tag
- example https://taginfo.openstreetmap.org/tags/highway=street_lamp#map
- https://taginfo.openstreetmap.org/taginfo/apidoc

It would be great to have a way to get those for tag [combinations](https://taginfo.openstreetmap.org/tags/highway=street_lamp#combinations), like `highway=street_lamp + operator=*`

**Comment by joto** [comment]
Taginfo pre-processes all the data for quick access. So there are thousands of images generated every day for all keys and tags. There is no way this approach will work for tag combinations, there are just too many of them. So what you are asking for would need a complete re-architecting of taginfo as well as much more ressources on the server. So, sorry, this is not going to happen.

Maybe the regional taginfo instances at https://taginfo.geofabrik.de/ can help you somehow.
