### ISSUE TITLE
history tab

### ISSUE THREAD

**Issue by Klumbumbus** [taginfo/taginfo#93]
It would be nice if there is one more tab called e.g. "history". It shows the number of a key/tag as a function of the time. So you can see if the number of a tag decreases or increases or if it increases slow or fast, or you can examine if and how a new tagging scheme is used/accepted by mappers, or...

In addition it would be nice if you can filter this graph (nodes, ways, relations)

Maybe this is very resource heavy. I think it would be enough if this graph is updated only once a week.

**Comment by tyrasd** [comment]
FYI: I'm currently working on a such a tool: https://github.com/tyrasd/taghistory – the goal is to also provide an [API](https://github.com/tyrasd/taghistory#api) which could be used for such a *history tab*.

**Comment by Klumbumbus** [comment]
Great!

**Comment by westnordost** [comment]
I love this tool, thank you @tyrasd 

I wonder if this could be integrated into taginfo. Some reasons that speak for it:
1. everybody knows taginfo, taginfo is *the* go-to place to learn about usage of tags to make educated tag decisions. (As a matter of fact, I only learnt of the existence of taghistory a few weeks ago)
2. both projects are C++ it seems
3. taginfo already knows which projects are using which tag(s). If taginfo would in the future record the history of the usage in projects, it would have the data necessary to put dots on the taghistory graph to mark big changes in usage - for example when an editor started offering a tag as a preset.
4. taghistory analyzes OSM history. As far as I know, this feature is missing in taginfo, for which reason the number of users using a tag (#222) cannot be shown. If taghistory is integrated (not just using taghistory's api but fully) into taginfo, taginfo would perhaps gain the groundwork necessary for this

**Comment by tyrasd** [comment]
taginfo now has this information as well: https://blog.jochentopf.com/2020-11-08-10-years-of-taginfo.html :tada:
